; Toprace URL: http://www.toprace.top

[ABOUT]
AUTHOR = BUG3721
VERSION = v1.2
DATE_RELEASE = 06-11-20
LIGHTS_COUNT = 
NOTES = 

[SOL]
HORIZON_OFFSET = 0.0
DOME_SIZE = 20000
SUN_DAWN = 1
SUN_DUSK = 1
FOG_LEVEL = 0.90
FOG_BLEND = 1.15
FOG_DISTANCE = 0.9
SMOG_MORNING = 0.05
SMOG_NOON = 0.1
SMOG_EVENING = 0.15
EXPOSURE_FIX = 1

[LIGHTING]
SPECULAR_MULT=1.0
LIT_MULT=1.0

[WIND]
DYNAMIC_FLAGS = AUTO

[INCLUDE]
INCLUDE = common/conditions.ini, common/materials_track.ini

[SOUNDBANK_0]
BANK = sfx/china_gp.bank
GUIDS = sfx/GUIDs.txt

[EVENT_0]
ID = racetrack/Helicopter
REVERB_RESPONSE = 1
VOLUME = 1.0
CAMERA_INTERIOR_MULT = 1.0
CAMERA_EXTERIOR_MULT = 1.0
CAMERA_TRACK_MULT = 1.0
RELATIVE_TO = helicopter_01
POSITION = 0, 0, 0
DIRECTION = 1, 1, 1
 
[EVENT_1]
ID = racetrack/Helicopter
REVERB_RESPONSE = 1
VOLUME = 1.0
CAMERA_INTERIOR_MULT = 1.0
CAMERA_EXTERIOR_MULT = 1.0
CAMERA_TRACK_MULT = 1.0
RELATIVE_TO = helicopter_02
POSITION = 0.0, 0.0, 0.0
DIRECTION = 1, 1, 1
 
[EVENT_2]
ID = racetrack/Helicopter
REVERB_RESPONSE = 1
VOLUME = 1.0
CAMERA_INTERIOR_MULT = 1.0
CAMERA_EXTERIOR_MULT = 1.0
CAMERA_TRACK_MULT = 1.0
RELATIVE_TO = helicopter_03
POSITION = 0.0, 0.0, 0.0
DIRECTION = 1, 1, 1
 
[EVENT_3]
ID = racetrack/Helicopter
REVERB_RESPONSE = 1
VOLUME = 1.0
CAMERA_INTERIOR_MULT = 1.0
CAMERA_EXTERIOR_MULT = 1.0
CAMERA_TRACK_MULT = 1.0
RELATIVE_TO = helicopter_04
POSITION = 0.0, 0.0, 0.0
DIRECTION = 1, 1, 1

[EVENT_4]
ID = racetrack/Planeprop
REVERB_RESPONSE = 0
VOLUME = 1.0
CAMERA_INTERIOR_MULT = 1
CAMERA_EXTERIOR_MULT = 1.0
CAMERA_TRACK_MULT = 1.0
RELATIVE_TO = airship
POSITION = 0.0, 0.0, 0.0
DIRECTION = 1, 1, 1

[LIGHT_SERIES_0]
ACTIVE=1
VISIBILITY_LEVEL=0
DESCRIPTION=
MATERIALS= fire
OFFSET=0,0,0
DIRECTION=DIRECTION=0,-1,0
SPOT=180
SPOT_SHARPNESS=0.76
RANGE=40
RANGE_GRADIENT_OFFSET=0.4
FADE_AT=1000
FADE_SMOOTH=40
CLUSTER_THRESHOLD=30
SINGLE_FREQUENCY=0.5
COLOR=200,60,35,0.5
COLOR_OFF=255,183,76,0
CONDITION=NIGHT_SMOOTH

[MATERIAL_ADJUSTMENT_0]
ACTIVE=1
VISIBILITY_LEVEL=0
DESCRIPTION=
MATERIALS= fire
KEY_0=ksEmissive
VALUE_0=234,121,36,0.5
VALUE_0_OFF=0, 0, 0
KEY_1=ksAlphaRef
VALUE_1=-193
VALUE_1_OFF=0, 0, 0
CONDITION=NIGHT_SMOOTH

[LIGHT_SERIES_1]
MATERIALS = obj_dayt_light_pole_002_LIT
OFFSET = 0,0,0
CLUSTER_THRESHOLD = 30
COLOR = 255, 229, 255, 0.06
SPOT = 180
RANGE = 125
RANGE_GRADIENT_OFFSET = 0.4
FADE_AT = 1000
FADE_SMOOTH = 50
DIRECTION = NORMAL
DIFFUSE_CONCENTRATION = 1
ACTIVE = 1
CONDITION = NIGHT_SMOOTH

[MATERIAL_ADJUSTMENT_1]
MATERIALS = obj_dayt_light_pole_002_LIT
KEY_0 = ksEmissive
VALUE_0 = 255, 229, 255, 1.5
VALUE_0_OFF = 0, 0, 0
ACTIVE = 1
CONDITION = NIGHT_SMOOTH

[LIGHT_SERIES_2]
ACTIVE = 1
DESCRIPTION = 
MATERIALS = 
DIRECTION = 0,-1,0
SPOT = 180
SPOT_SHARPNESS = 0.5
RANGE = 100
RANGE_GRADIENT_OFFSET = 0.4
FADE_AT = 1000
FADE_SMOOTH = 25
COLOR = 255, 229, 255, 0.055
CLUSTER_THRESHOLD = 18
DIFFUSE_CONCENTRATION = 0.5
CONDITION = NIGHT_SMOOTH

[MATERIAL_ADJUSTMENT_2]
ACTIVE = 1
VISIBILITY_LEVEL = 1
DESCRIPTION = 
MATERIALS = 
KEY_0 = ksEmissive
VALUE_0 = 255, 229, 255, 0.05
VALUE_0_OFF = 0, 0, 0
KEY_1 = ksAlphaRef
VALUE_1 = -193
VALUE_1_OFF = 0
CONDITION = NIGHT_SMOOTH

[LIGHT_SERIES_3]
ACTIVE = 1
DESCRIPTION = 
MATERIALS = material_sha_building_glasstower_a_01, sha_building_skybridge_c, CoastGuardHelicopter_Glass,
OFFSET = 0,0,0
DIRECTION = 0,-0.1,0
SPOT = 180
SPOT_SHARPNESS = 0.5
RANGE = 40
RANGE_GRADIENT_OFFSET = 0.4
FADE_AT = 1000
FADE_SMOOTH = 25
COLOR = 255, 229, 255, 0.04
CLUSTER_THRESHOLD = 18
DIFFUSE_CONCENTRATION = 0.5
CONDITION = NIGHT_SMOOTH

[MATERIAL_ADJUSTMENT_3]
ACTIVE = 1
VISIBILITY_LEVEL = 1
DESCRIPTION = 
MATERIALS = material_sha_building_glasstower_a_01, sha_building_skybridge_c, CoastGuardHelicopter_Glass, sha_infrastructure_brollyroof_b, screen, Screen_2
KEY_0 = ksEmissive
VALUE_0 = 255, 229, 255, 0.003
VALUE_0_OFF = 0, 0, 0
KEY_1 = ksAlphaRef
VALUE_1 = -193
VALUE_1_OFF = 0
CONDITION = NIGHT_SMOOTH

[LIGHT_SERIES_4]
ACTIVE = 1
DESCRIPTION = 
MATERIALS = obj_dayt_light_spot_001_LIT
OFFSET = 0,0,0
DIRECTION = 0,-1,0
SPOT = 180
SPOT_SHARPNESS = 0.5
RANGE = 110
RANGE_GRADIENT_OFFSET = 0.4
FADE_AT = 1000
FADE_SMOOTH = 25
COLOR = 255, 229, 255, 0.03
CLUSTER_THRESHOLD = 18
DIFFUSE_CONCENTRATION = 0.5
CONDITION = NIGHT_SMOOTH

[MATERIAL_ADJUSTMENT_4]
ACTIVE = 1
VISIBILITY_LEVEL = 1
DESCRIPTION = 
MATERIALS = obj_dayt_light_spot_001_LIT
KEY_0 = ksEmissive
VALUE_0 = 255, 229, 255, 1.2
VALUE_0_OFF = 0, 0, 0
KEY_1 = ksAlphaRef
VALUE_1 = -193
VALUE_1_OFF = 0
CONDITION = NIGHT_SMOOTH

[LIGHT_SERIES_5]
ACTIVE = 1
DESCRIPTION = sha_building_skybridge_c, sha_building_glasstower_a_03, CoastGuardHelicopter
MATERIALS = 
OFFSET = 0,0,0
DIRECTION = 0,-1,0
SPOT = 180
SPOT_SHARPNESS = 0.5
RANGE = 50
RANGE_GRADIENT_OFFSET = 0.4
FADE_AT = 1000
FADE_SMOOTH = 25
COLOR = 255, 229, 255, 0.06
CLUSTER_THRESHOLD = 18
DIFFUSE_CONCENTRATION = 0.5
CONDITION = NIGHT_SMOOTH

[MATERIAL_ADJUSTMENT_5]
ACTIVE = 1
VISIBILITY_LEVEL = 1
DESCRIPTION = 
MATERIALS = sha_building_skybridge_c, sha_building_glasstower_a_03, CoastGuardHelicopter, billboard24
KEY_0 = ksEmissive
VALUE_0 = 255, 229, 255, 0.002
VALUE_0_OFF = 0, 0, 0
KEY_1 = ksAlphaRef
VALUE_1 = -193
VALUE_1_OFF = 0
CONDITION = NIGHT_SMOOTH

[LIGHT_SERIES_6]
ACTIVE = 1
DESCRIPTION = CoastGuardHelicopter, Rotor, balloon, Blimp.001, recovery_crane_a, standard_2!0, standard_2
MATERIALS = 
OFFSET = 0,0,0
DIRECTION = 0,0,0
SPOT = 180
SPOT_SHARPNESS = 0.5
RANGE = 50
RANGE_GRADIENT_OFFSET = 0.4
FADE_AT = 1000
FADE_SMOOTH = 25
COLOR = 255, 229, 255, 0.02
CLUSTER_THRESHOLD = 18
DIFFUSE_CONCENTRATION = 0.5
CONDITION = NIGHT_SMOOTH

[MATERIAL_ADJUSTMENT_6]
ACTIVE = 1
VISIBILITY_LEVEL = 1
DESCRIPTION = 
MATERIALS = CoastGuardHelicopter, Rotor, balloon, Blimp.001, recovery_crane_a, standard_2!0, standard_2
KEY_0 = ksEmissive
VALUE_0 = 255, 229, 255, 0.0004
VALUE_0_OFF = 0, 0, 0
KEY_1 = ksAlphaRef
VALUE_1 = -193
VALUE_1_OFF = 0
CONDITION = NIGHT_SMOOTH

[LIGHT_SERIES_7]
ACTIVE = 1
DESCRIPTION = 
MATERIALS = sha_hut_marshalls_a
OFFSET = 0,0,0
DIRECTION = 0,-0.9,0
SPOT = 180
SPOT_SHARPNESS = 0.5
RANGE = 40
RANGE_GRADIENT_OFFSET = 0.4
FADE_AT = 1000
FADE_SMOOTH = 25
COLOR = 255, 229, 255, 0.02
CLUSTER_THRESHOLD = 18
DIFFUSE_CONCENTRATION = 0.5
CONDITION = NIGHT_SMOOTH

[MATERIAL_ADJUSTMENT_7]
ACTIVE = 1
VISIBILITY_LEVEL = 1
DESCRIPTION = 
MATERIALS = sha_hut_marshalls_a, marshall, sha_distance, Traliccio_BIG, crane_distan, Radio_towwer, aa_1, tower_redwhi
KEY_0 = ksEmissive
VALUE_0 = 255, 229, 255, 0.0008
VALUE_0_OFF = 0, 0, 0
KEY_1 = ksAlphaRef
VALUE_1 = -193
VALUE_1_OFF = 0
CONDITION = NIGHT_SMOOTH

[LIGHT_SERIES_8]
ACTIVE = 1
DESCRIPTION = 
MATERIALS = sha_infrastructure_brollyroof_b
OFFSET = 0,0,0
DIRECTION = 0,-0.1,0
SPOT = 150
SPOT_SHARPNESS = 0.5
RANGE = 40
RANGE_GRADIENT_OFFSET = 0.4
FADE_AT = 1000
FADE_SMOOTH = 25
COLOR = 255, 229, 255, 0.05
CLUSTER_THRESHOLD = 18
DIFFUSE_CONCENTRATION = 0.5
CONDITION = NIGHT_SMOOTH

[MATERIAL_ADJUSTMENT_8]
ACTIVE = 1
VISIBILITY_LEVEL = 1
DESCRIPTION = 
MATERIALS = sha_infrastructure_brollyroof_b
KEY_0 = ksEmissive
VALUE_0 = 255, 229, 255, 0.002
VALUE_0_OFF = 0, 0, 0
KEY_1 = ksAlphaRef
VALUE_1 = -193
VALUE_1_OFF = 0
CONDITION = NIGHT_SMOOTH

[Material_Water]
Materials = c34
UseAlphaFromNormal = 1
UseRecommendedTextures = 1
UseRecommendedDetailTexture = 1
UseNormalMapTwice = 1
Type = POND

[GRASS_FX]
GRASS_MATERIALS = grass, c32
GRASS_MESHES = 
OCCLUDING_MESHES = 
OCCLUDING_MATERIALS = 
OCCLUDING_MATERIALS_ALPHA = Kerb_giallo, c9!0
ORIGINAL_GRASS_MATERIALS= 
MASK_BLUR = 1
SHAPE_SIZE = 3.5, 1  
SHAPE_TIDY = 0.5   
SHAPE_CUT = 0.5    
SHAPE_WIDTH = 2.0
TRIM_PERIOD = 365 
MASK_MAIN_THRESHOLD = 1.0
MASK_RED_THRESHOLD = 0.05
MASK_MIN_LUMINANCE = 0.006
MASK_MAX_LUMINANCE = 1.0
TEXTURE =  grass_fx/highlands.dds
TEXTURE_GRID =8, 3

[GRASS_FX_TEXTURE_GROUP_0]
PIECE_0 = 1, 1
PIECE_0_CHANCE = 0.25
PIECE_1 = 1, 2, 2, 1
PIECE_1_CHANCE = 0.05
PIECE_2 = 4, 1, 2, 2
PIECE_2_CHANCE = 0.5
PIECE_3 = 6, 1
PIECE_4 = 7, 1
PIECE_5 = 8, 1

[GRASS_FX_CONFIGURATION_A]
SHAPE_SIZE = 1.0, 3.5
SHAPE_CUT = 1, 0
SHAPE_TIDY = 1, 0.5
TRIM_PERIOD = 30
MASK_MAIN_THRESHOLD = 0.6
MASK_MAX_LUMINANCE = 0.1
TEXTURE_BASE_CHANCE = 1
TEXTURE_GROUP_0_CHANCE = 0.2

[GRASS_FX_CONFIGURATION_B]
SHAPE_SIZE = 3.5, 6.0
SHAPE_CUT = 0
SHAPE_TIDY = 0
TRIM_PERIOD = 365
MASK_MAIN_THRESHOLD = 0.4
MASK_MAX_LUMINANCE = 0.105
TEXTURE_BASE_CHANCE = 1
TEXTURE_GROUP_0_CHANCE = 0.5

[GRASS_FX_ADJUSTMENT_...]
MATERIALS = 
MAP = A

[GRASS_FX_ADJUSTMENT_...]
MATERIALS = 
MAP = B

[RAIN_FX]
PUDDLES_MATERIALS = asphalt_road, Line_asf, c22, RUG_blu, Out, billboard34, c14, c9!0, material #110, c10, c13, billboard22, c21, c18, billboard21, c20, high_floor_sponsors_05, Kerb_giallo, Pit_lane, LInea_PITNew, billboard37, billboard99, billboard19, billboard09, sha_barrier_pitwall_b, Pat_petronas
SOAKING_MATERIALS = 
SMOOTH_MATERIALS = 
ROUGH_MATERIALS = 

[ANIMATED_...]
NODE = helicopter_01
ANIMATION = 
DURATION = 192

[ANIMATED_...]
NODE = helicopter_02
ANIMATION = 
DURATION = 120

[SHADER_REPLACEMENT_...]
MATERIALS = Rotor
SHADER = stPerPixelNM_UVflow
PROP_0 = offsetNMSpeed, 6.3, 0

[SHADER_REPLACEMENT_...]
MATERIALS = Rotor2
SHADER = stPerPixelNM_UVflow
PROP_0 = offsetNMSpeed, 6.3, 0

[CONDITION_...]
NAME = BLINK
INPUT = ONE
FLASHING_FREQUENCY = 5
FLASHING_SMOOTHNESS = 0
FLASHING_SKIP_OFF_STATE = 0
FLASHING_NOISE_AMPLITUDE = 0
FLASHING_MIN_VALUE = 0.0
FLASHING_SYNCED = 1

[CONDITION_...]
NAME = BLINK_ALT
INPUT = ONE
FLASHING_FREQUENCY = -5
FLASHING_SMOOTHNESS = 0
FLASHING_SKIP_OFF_STATE = 0
FLASHING_NOISE_AMPLITUDE = 0
FLASHING_MIN_VALUE = 0.0
FLASHING_SYNCED = 1

[MATERIAL_ADJUSTMENT_...]
ACTIVE = 1
DESCRIPTION = light on
MATERIALS = lg_marshal_light_b_screen,
KEY_0 = ksEmissive
VALUE_0 = 0,255,0,0.05
VALUE_0_OFF = 0
CONDITION = BLINK

[MATERIAL_ADJUSTMENT_...]
ACTIVE = 1
DESCRIPTION = heli green
MATERIALS = heligreen, Hughes500_GreenLight
KEY_0 = ksEmissive
VALUE_0 = 0,255,0,1
VALUE_0_OFF = 0
CONDITION = BLINK

[MATERIAL_ADJUSTMENT_...]
ACTIVE = 1
DESCRIPTION = heli red
MATERIALS = helired, Hughes500_RedLight
KEY_0 = ksEmissive
VALUE_0 = 255,0,0,2
VALUE_0_OFF = 0
CONDITION = BLINK_ALT

[MATERIAL_ADJUSTMENT_...]
ACTIVE = 1
DESCRIPTION = heli cockpit
MATERIALS = heliinside, Hughes500_Navlights
KEY_0 = ksEmissive
VALUE_0 = 55,255,55,0.25
VALUE_0_OFF = 0
CONDITION = NIGHT_SMOOTH

[MATERIAL_ADJUSTMENT_...]
ACTIVE = 1
VISIBILITY_LEVEL = 1
DESCRIPTION = make heli sky flooder visible at night
MATERIALS = helispot
KEY_0 = alpha
VALUE_0 = 0.5
VALUE_0_OFF = ORIGINAL
KEY_1 = ksAlphaRef
VALUE_1 = 1
VALUE_1_OFF = ORIGINAL
KEY_2 = ksDiffuse
VALUE_2 = 1
VALUE_2_OFF = ORIGINAL
BLEND_MODE = ALPHA_BLEND
 ;BLEND_MODE=ALPHA_TEST
CONDITION = NIGHT_SMOOTH

[MATERIAL_ADJUSTMENT_...]
ACTIVE = 1
VISIBILITY_LEVEL = 1
DESCRIPTION = make heli sky flooder glow
MATERIALS = helispot
KEY_0 = ksEmissive
VALUE_0 = 5
VALUE_0_OFF = ORIGINAL
CONDITION = NIGHT_SMOOTH

[ANIMATED_...]
NODE = Blimp
ANIMATION = 
DURATION = 1925

[SHADER_REPLACEMENT_...]
DESCRIPTION=paddock lights replacement
MATERIALS=Blimp.001
SHADER=ksPerPixelMultiMap_emissive
RESOURCE_4=txEmissive
RESOURCE_REF_4=txMaps

[MATERIAL_ADJUSTMENT_...]
MATERIALS=Blimp.001
KEY_0=ksEmissive
VALUE_0=255,255,255,0.1
VALUE_0_OFF=0
KEY_1=ksAlphaRef
VALUE_1=-193
VALUE_1_OFF=0
CONDITION=NIGHT_SMOOTH

[LIGHT_...]
ACTIVE=1
DESCRIPTION=blimp light
POSITION = 0, -15, 0
DIRECTION = 0, 1, 0
RELATIVE_TO = Blimp_geo_001
SPOT = 180
SPOT_SHARPNESS = 0.5
RANGE = 10
RANGE_GRADIENT_OFFSET = 0.2
COLOR = 100
VOLUMETRIC_LIGHT = 1
