[DEFAULTS]
TRACK_FILE = china_2021.kn5

[MODEL_REPLACEMENT_...]
ACTIVE = 1
FILE = $TRACK_FILE
INSERT=crowds_vk.kn5
INSERT_AFTER=objtribun004

[SPECTATORS]
MESHES = crowd?


[SHADER_REPLACEMENT_...]
MATERIALS = crowds
BLEND_MODE = ALPHA_TEST
SHADER = ksPerPixelAT
IS_TRANSPARENT = 0
PROP_... = ksDiffuse, 0.15
PROP_... = ksAmbient, 0.33
PROP_... = ksSpecular, 0.0

[MESH_ADJUSTMENT_...]
ACTIVE = 1
MESHES = spectator_ground, spectator_ground?
IS_RENDERABLE = 0

; ---------------------- waving flag SHADER ---------------

[SHADER_REPLACEMENT_...]
MATERIALS = FlagAni01
SHADER = stPerPixelNM_UVflow
RESOURCE_0 = txDiffuse
RESOURCE_TEXTURE_0 = FlagWaveAni01.dds
RESOURCE_1 = txNormal
RESOURCE_TEXTURE_1 = FlagWaveAni01.dds
PROP_...= ksAmbient, 0.5
PROP_...= ksDiffuse, 0.5
PROP_...= offsetDSpeed, 0.0, 1.0
PROP_...= offsetNMSpeed, 0.0, 1.0
PROP_...= pauseTiming, .08, -1
 ;IS_TRANSPARENT = 1
BLEND_MODE = ALPHA_TEST

[SHADER_REPLACEMENT_...]
MATERIALS = FlagAni02
SHADER = stPerPixelNM_UVflow
RESOURCE_0 = txDiffuse
RESOURCE_TEXTURE_0 = FlagWaveAni02.dds
RESOURCE_1 = txNormal
RESOURCE_TEXTURE_1 = FlagWaveAni02.dds
PROP_...= ksAmbient, 0.5
PROP_...= ksDiffuse, 0.5
PROP_...= offsetDSpeed, 0.0, 1.0
PROP_...= offsetNMSpeed, 0.0, 1.0
PROP_...= pauseTiming, .08, -1
 ;IS_TRANSPARENT = 1
BLEND_MODE = ALPHA_TEST

[SHADER_REPLACEMENT_...]
MATERIALS = FlagAni03
SHADER = stPerPixelNM_UVflow
RESOURCE_0 = txDiffuse
RESOURCE_TEXTURE_0 = FlagWaveAni03.dds
RESOURCE_1 = txNormal
RESOURCE_TEXTURE_1 = FlagWaveAni03.dds
PROP_...= ksAmbient, 0.5
PROP_...= ksDiffuse, 0.5
PROP_...= offsetDSpeed, 0.0, 1.0
PROP_...= offsetNMSpeed, 0.0, 1.0
PROP_...= pauseTiming, .08, -1
 ;IS_TRANSPARENT = 1
BLEND_MODE = ALPHA_TEST

[SHADER_REPLACEMENT_...]
MATERIALS = FlagAni04
SHADER = stPerPixelNM_UVflow
RESOURCE_0 = txDiffuse
RESOURCE_TEXTURE_0 = FlagWaveAni04.dds
RESOURCE_1 = txNormal
RESOURCE_TEXTURE_1 = FlagWaveAni04.dds
PROP_...= ksAmbient, 0.5
PROP_...= ksDiffuse, 0.5
PROP_...= offsetDSpeed, 0.0, 1.0
PROP_...= offsetNMSpeed, 0.0, 1.0
PROP_...= pauseTiming, .08, -1
IS_TRANSPARENT = 0
BLEND_MODE = ALPHA_TEST
