[DEFAULTS]
TRACK_FILE = china_2021.kn5
GRASS_MATS =  grass, c32
3D_Grass__track = roada327.001
OCLUDDING_MATS = Kerb_giallo, c9!0


; ------------------------------------ GRASS ----------------------------

[GRASS_FX]
 ; mention all the materials you wanna use
 ; a separate MATERIALS= is later in GRASS_FX_ADJUSTMENT_9021
GRASS_MATERIALS = $GRASS_MATS
 ; this is for hiding original grass, only hide one material here
ORIGINAL_GRASS_MATERIALS = $3D_Grass__track, WEEDTIRES
ORIGINAL_GRASS_MESHES = crowd_standing_1_KSLAYER5
OCCLUDING_MATERIALS_ALPHA = $OCLUDDING_MATS
 ; leave it empty! and in!
OCCLUDING_MATERIALS = $Road__track , GSTAND_01,

MASK_MAIN_THRESHOLD = 0.05
MASK_RED_THRESHOLD = 0.02
MASK_MIN_LUMINANCE = -1 ; 09002255


 ; load texture
TEXTURE = grass_fx/highlands.dds  ; located next to config file; if not found there, patch would look in its textures folder
TEXTURE_GRID = 8, 3  ; columns and rows

 ; hold on, not done yet, lets
 ; define a grass group0 and some pieces from texture

[GRASS_FX_TEXTURE_GROUP_0]
PIECE_0 = 1, 1 ; first piece stars with cell at (1; 1), coordinates skip first row, so it would be that piece with a single yellow flower
PIECE_0_SIZE_MULT = .3,.4
PIECE_0_CHANCE = 0.1
PIECE_1 = 2, 1 ; second piece, takes a single cell as well
PIECE_1_SIZE_MULT = .3,.3
PIECE_1_CHANCE = 0.1
PIECE_2 = 1, 12, 1, 1 ; third piece, with yellow and white flower, taking 21 slots
PIECE_2_CHANCE = 0.5 ; would appear 10 times less often then first two pieces
PIECE_3 = 2, 2 ; two more only green pieces
PIECE_3_SIZE_MULT = 1, 1
PIECE_4_SIZE_MULT = 1, 1

 ; define some bigger pieces in group1

[GRASS_FX_TEXTURE_GROUP_1]
PIECE_5 = 1, 1, 1, 2 ; piece taking 12 slots, the one with purple flowers
PIECE_5_CHANCE = 0.1
PIECE_5_SIZE_MULT = .75, 1.1 ; default size multiplier is based on size in cells, overriding
PIECE_6 = 1, 1, 2, 2 ; piece taking 22 slots, the one with long gras
PIECE_6_CHANCE = 0.25
PIECE_6_SIZE_MULT = .5,.6 ; default size multiplier is based on size in cells, overriding

 ;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
 ; MAP A, cut weekly, using both groups in different amounts

[GRASS_FX_CONFIGURATION_A]
TRIM_PERIOD = MONDAY
SHAPE_SIZE = 1.1, 0.7 ; uncut, after-cut size
SHAPE_TIDY = 0.5
SHAPE_CUT = 0.5
TEXTURE_BASE_CHANCE = 1       ; chance of regular grass to spawn
TEXTURE_GROUP_0_CHANCE = 1.0  ; chance of first group to spawn
TEXTURE_GROUP_1_CHANCE = 2

 ; finally apply MAP A to nearby track grass
[GRASS_FX_ADJUSTMENT_...]
MATERIALS = grass
MAP = A

[GRASS_FX_CONFIGURATION_B]
DESCRIPTION = longer grass for the outside.
SHAPE_SIZE = 0.7
TEXTURE_BASE_CHANCE = 0.0       ; chance of regular grass to spawn
TEXTURE_GROUP_0_CHANCE = 0.01  ; chance of first group to spawn
TEXTURE_GROUP_1_CHANCE = 0.0

[GRASS_FX_ADJUSTMENT_...]
MATERIALS = c32
MAP = B

[SHADER_REPLACEMENT_...]
DESCRIPTION=main close grass
MATERIALS=grass
SHADER=ksMultilayer
RESOURCE_0=txDiffuse
RESOURCE_COLOR_0=1,1,1
RESOURCE_1=txMask
RESOURCE_FILE_1=grass_mask3.dds
RESOURCE_2=txDetailR
RESOURCE_TEXTURE_2=grass-detail26b.dds
RESOURCE_3=txDetailG
; RESOURCE_COLOR_3=0,0,1
RESOURCE_FILE_3=GrassGreenDETAIL_d.dds
RESOURCE_4=txDetailB
RESOURCE_FILE_4=sbancamento_C_d.dds
RESOURCE_5=txDetailA
RESOURCE_COLOR_5 = 0,0,0;
PROP_... = ksDiffuse, 0.25
PROP_... = ksAmbient, 0.25
PROP_... = magicMult, 1.0
PROP_... = multR, 0.1
PROP_... = multG, 0.02
PROP_... = multB, 0.1
PROP_... = multA, 0.15, 0.15


[SHADER_REPLACEMENT_...]
DESCRIPTION=main close grass
MATERIALS=c32
SHADER=ksMultilayer
RESOURCE_0=txDiffuse
RESOURCE_TEXTURE_0=DiffuseTerreno004.dds
RESOURCE_1=txMask
RESOURCE_TEXTURE_1=Terreno200_Map_B_11.dds
RESOURCE_2=txDetailR
RESOURCE_TEXTURE_2=grass9.dds
; RESOURCE_TEXTURE_2=grass-detail26b.dds
RESOURCE_3=txDetailG
; RESOURCE_COLOR_3=0,0,1
RESOURCE_TEXTURE_3=grass9.dds
RESOURCE_4=txDetailB
; RESOURCE_COLOR_3=0,0,1
RESOURCE_TEXTURE_4=sbancamento_C.dds
RESOURCE_5=txDetailA
RESOURCE_COLOR_5 = 0,0,0;
PROP_... = ksDiffuse, 0.35
PROP_... = ksAmbient, 0.35
PROP_... = magicMult, 1.0
PROP_... = multR, 0.4
PROP_... = multG, 0.2
PROP_... = multB, 0.3
PROP_... = multA, 0.15, 0.15


[SHADER_REPLACEMENT_...]
MATERIALS = aa_1, aa_2, aa_3, sha_building_skybridge_c, aa_2!0, sha_grandstand_underbrolly_b_01
PROP_1 = ksDiffuse, 0.25
PROP_2 = ksAmbient, 0.25

[SHADER_REPLACEMENT_...]
MATERIALS = sha_grandstand_group_d
PROP_1 = ksDiffuse, 0.2
PROP_2 = ksAmbient, 0.2


[SHADER_REPLACEMENT_...]
MATERIALS = sha_infrastructure_brollyroof_b
RESOURCE_0=txDiffuse
RESOURCE_FILE_0=sha_infrastructure_brollyroof_a_ALFA5.dds
PROP_1 = ksDiffuse, 0.4
PROP_2 = ksAmbient, 0.6
PROP_3 = ksSpecular, 0.0

[SHADER_REPLACEMENT_...]
MATERIALS = c9!0
RESOURCE_0=txDiffuse
RESOURCE_FILE_0=sha_rumble_a_01_PAT_drk4.dds
PROP_1 = ksDiffuse, 0.25
PROP_2 = ksAmbient, 0.25
PROP_3 = ksSpecular, 0.0
