; Toprace URL: http://www.toprace.top

[ABOUT]
AUTHOR = BUG3721
VERSION = v1.1
DATE_RELEASE = 21-12-20
LIGHTS_COUNT = 
NOTES = 

[SOL]
HORIZON_OFFSET=0.0
DOME_SIZE=20000
SUN_DAWN=1
SUN_DUSK=1
FOG_LEVEL=0.85
FOG_BLEND=1.1
FOG_DISTANCE=1.05
SMOG_MORNING=0.25
SMOG_NOON=0.45
SMOG_EVENING=0.7
EXPOSURE_FIX=1

[LIGHTING]
LIT_MULT=1.0
SPECULAR_MULT=1.0
CAR_LIGHTS_LIT_MULT=1.0

[DISTANT_GLOW]
THRESHOLD = 25
SHARED_THRESHOLD = 25

[INCLUDE]
INCLUDE = common/conditions.ini, common/materials_track.ini

[SOUNDBANK_0]
BANK = sfx/tr_goldenport.bank
GUIDS = sfx/GUIDs.txt

[EVENT_0]
ID = racetrack/Helicopter
REVERB_RESPONSE = 1
VOLUME = 1.0
CAMERA_INTERIOR_MULT = 1.0
CAMERA_EXTERIOR_MULT = 1.0
CAMERA_TRACK_MULT = 1.0
RELATIVE_TO = helicopter_01
POSITION = 0, 0, 0
DIRECTION = 1, 1, 1
 
[EVENT_1]
ID = racetrack/Helicopter
REVERB_RESPONSE = 1
VOLUME = 1.0
CAMERA_INTERIOR_MULT = 1.0
CAMERA_EXTERIOR_MULT = 1.0
CAMERA_TRACK_MULT = 1.0
RELATIVE_TO = helicopter_02
POSITION = 0.0, 0.0, 0.0
DIRECTION = 1, 1, 1

[LIGHT_SERIES_0]
ACTIVE=1
VISIBILITY_LEVEL=0
DESCRIPTION=all big 4 spotted lights
MATERIALS= diangan01
OFFSET=0,0,0
DIRECTION=DIRECTION=0,-1,0
SPOT=180
SPOT_SHARPNESS=0.76
RANGE=70
RANGE_GRADIENT_OFFSET=0.4
FADE_AT=1000
FADE_SMOOTH=40
CLUSTER_THRESHOLD=30
SINGLE_FREQUENCY=0.5
COLOR=234,121,36,0.05
COLOR_OFF=255,183,76,0
CONDITION=NIGHT_SMOOTH

[MATERIAL_ADJUSTMENT_0]
ACTIVE=1
VISIBILITY_LEVEL=0
DESCRIPTION=all big 4 spotted lights glow
MATERIALS= diangan01
KEY_0=ksEmissive
VALUE_0=234,121,36,0.5
VALUE_0_OFF=0, 0, 0
KEY_1=ksAlphaRef
VALUE_1=-193
VALUE_1_OFF=0, 0, 0
CONDITION=NIGHT_SMOOTH

[LIGHT_SERIES_1]
ACTIVE = 1
DESCRIPTION = 
MATERIALS = lamp_square_a_01, electric
OFFSET = 0,0,0
DIRECTION = 0,-1,0
SPOT = 180
SPOT_SHARPNESS = 0.5
RANGE = 40
RANGE_GRADIENT_OFFSET = 0.4
FADE_AT = 1000
FADE_SMOOTH = 25
COLOR = 255, 229, 255, 0.05
CLUSTER_THRESHOLD = 18
DIFFUSE_CONCENTRATION = 0.5
CONDITION = NIGHT_SMOOTH

[MATERIAL_ADJUSTMENT_1]
ACTIVE = 1
VISIBILITY_LEVEL = 1
DESCRIPTION = 
MATERIALS = lamp_square_a_01, electric
KEY_0 = ksEmissive
VALUE_0 = 255, 229, 255, 0.5
VALUE_0_OFF = 0, 0, 0
KEY_1 = ksAlphaRef
VALUE_1 = -193
VALUE_1_OFF = 0
CONDITION = NIGHT_SMOOTH


[Material_Water]
Materials = weatr
UseAlphaFromNormal = 1
UseRecommendedTextures = 0
UseRecommendedDetailTexture = 1
UseNormalMapTwice = 1
Type = POND

[GRASS_FX]
GRASS_MATERIALS = grasa_ku, grasa01, grasa_bian02, grasa03, grasa_df, grvl_bian, grasa_full01, roadcp01, grasa_bian01, grasa_ku
GRASS_MESHES = 
OCCLUDING_MESHES = 
OCCLUDING_MATERIALS = 
OCCLUDING_MATERIALS_ALPHA = 
ORIGINAL_GRASS_MATERIALS= cao01b, cao01a
TRIM_PERIOD = THURSDAY
MASK_BLUR = 1
MASK_MAIN_THRESHOLD = 0.75
SHAPE_SIZE = 2.5, 2.25
SHAPE_TIDY = 1, 0.5
SHAPE_CUT = 1, 0
TEXTURE = grass_fx/highlands.dds
TEXTURE_GRID = 8, 3

[GRASS_FX_TEXTURE_GROUP_0]
PIECE_0 = 1, 1
PIECE_1 = 1, 2, 2, 1
PIECE_1_CHANCE = 0.05
PIECE_2 = 4, 1, 2, 2
PIECE_2_CHANCE = 0.75
PIECE_3 = 6, 1
PIECE_4 = 7, 1
PIECE_5 = 8, 1

[GRASS_FX_CONFIGURATION_A]
TEXTURE_BASE_CHANCE = 1
TEXTURE_GROUP_0_CHANCE = 0.125
MASK_MAIN_THRESHOLD = 0.75
TRIM_PERIOD = THURSDAY
SHAPE_SIZE = 2.5, 2.25
SHAPE_TIDY = 1, 0.5
SHAPE_CUT = 1, 0

[GRASS_FX_CONFIGURATION_B]
TEXTURE_BASE_CHANCE = 1
TEXTURE_GROUP_0_CHANCE = 0.125
MASK_MAIN_THRESHOLD = 0.25
TRIM_PERIOD = 30
SHAPE_SIZE = 2.5, 4.0
SHAPE_TIDY = 0.5, 0
SHAPE_CUT = 1, 0

[INCLUDE: common/grass_fx.ini]

[GRASS_FX_ADJUSTMENT_...]
MATERIALS = grasa_ku, grasa_full01
MAP = A

@ = GrassFX_ExtraArea, Map = B, Center = "120, 0, 20", Range = 90, Fade = 55, Aspect = 1.25, Angle = 90
@ = GrassFX_ExtraArea, Map = B, Center = "-35, 0, 130", Range = 90, Fade = 50, Aspect = 1.5, Angle = 40
@ = GrassFX_ExtraArea, Map = B, Center = "-410, 0, -235", Range = 155, Fade = 50, Aspect = 3.5, Angle = -15
@ = GrassFX_ExtraArea, Map = B, Center = "-105, 0, -160", Range = 200, Fade = 50, Aspect = 10, Angle = -17.5
@ = GrassFX_ExtraArea, Map = B, Center = "470, 0, 50", Range = 85, Fade = 50, Aspect = 1.5, Angle = 90
@ = GrassFX_ExtraArea, Map = B, Center = "250, 0, 65", Range = 140, Fade = 50, Aspect = 10, Angle = 2
@ = GrassFX_ExtraArea, Map = B, Center = "-180, 0, -40", Range = 160, Fade = 50, Aspect = 1.65, Angle = -20

[RAIN_FX]
PUDDLES_MATERIALS = road_pit05, road_pit07, road01, material #27, material #28, road_pit01, road_pit02, wall01, wall08, roadas, roadas01, road_podium, road_pit04, road_pit03, wall_bian02(b), wall07
SOAKING_MATERIALS = 
SMOOTH_MATERIALS = 
ROUGH_MATERIALS =

[ANIMATED_...]
NODE = helicopter_01
ANIMATION = 
DURATION = 192

[ANIMATED_...]
NODE = helicopter_02
ANIMATION = 
DURATION = 120

[SHADER_REPLACEMENT_...]
MATERIALS = Rotor
SHADER = stPerPixelNM_UVflow
PROP_0 = offsetNMSpeed, 6.3, 0

[SHADER_REPLACEMENT_...]
MATERIALS = Rotor2
SHADER = stPerPixelNM_UVflow
PROP_0 = offsetNMSpeed, 6.3, 0

[CONDITION_...]
NAME = BLINK
INPUT = ONE
FLASHING_FREQUENCY = 5
FLASHING_SMOOTHNESS = 0
FLASHING_SKIP_OFF_STATE = 0
FLASHING_NOISE_AMPLITUDE = 0
FLASHING_MIN_VALUE = 0.0
FLASHING_SYNCED = 1

[CONDITION_...]
NAME = BLINK_ALT
INPUT = ONE
FLASHING_FREQUENCY = -5
FLASHING_SMOOTHNESS = 0
FLASHING_SKIP_OFF_STATE = 0
FLASHING_NOISE_AMPLITUDE = 0
FLASHING_MIN_VALUE = 0.0
FLASHING_SYNCED = 1

[MATERIAL_ADJUSTMENT_...]
ACTIVE = 1
DESCRIPTION = heli green
MATERIALS = heligreen, Hughes500_GreenLight
KEY_0 = ksEmissive
VALUE_0 = 0,255,0,1
VALUE_0_OFF = 0
CONDITION = BLINK

[MATERIAL_ADJUSTMENT_...]
ACTIVE = 1
DESCRIPTION = heli red
MATERIALS = helired, Hughes500_RedLight
KEY_0 = ksEmissive
VALUE_0 = 255,0,0,2
VALUE_0_OFF = 0
CONDITION = BLINK_ALT

[MATERIAL_ADJUSTMENT_...]
ACTIVE = 1
DESCRIPTION = heli cockpit
MATERIALS = heliinside, Hughes500_Navlights
KEY_0 = ksEmissive
VALUE_0 = 55,255,55,0.25
VALUE_0_OFF = 0
CONDITION = NIGHT_SMOOTH

[MATERIAL_ADJUSTMENT_...]
ACTIVE = 1
VISIBILITY_LEVEL = 1
DESCRIPTION = make heli sky flooder visible at night
MATERIALS = helispot
KEY_0 = alpha
VALUE_0 = 0.5
VALUE_0_OFF = ORIGINAL
KEY_1 = ksAlphaRef
VALUE_1 = 1
VALUE_1_OFF = ORIGINAL
KEY_2 = ksDiffuse
VALUE_2 = 1
VALUE_2_OFF = ORIGINAL
BLEND_MODE = ALPHA_BLEND
 ;BLEND_MODE=ALPHA_TEST
CONDITION = NIGHT_SMOOTH

[MATERIAL_ADJUSTMENT_...]
ACTIVE = 1
VISIBILITY_LEVEL = 1
DESCRIPTION = make heli sky flooder glow
MATERIALS = helispot
KEY_0 = ksEmissive
VALUE_0 = 5
VALUE_0_OFF = ORIGINAL
CONDITION = NIGHT_SMOOTH
