[ABOUT]
AUTHOR = shin956
VERSION = 1.0
DATE_RELEASE = 11/2/2020
NOTES = sanya_eprix

[LIGHTING]
SPECULAR_MULT=1.0
LIT_MULT=1.0
CAR_LIGHTS_LIT_MULT=1.0

[INCLUDE]
INCLUDE = common\conditions.ini, common\materials_base.ini, common\materials_track.ini

[Material_Water]
Materials = roada2629
Type = LAKE

[GRASS_FX]
GRASS_MATERIALS = grass1807
OCCLUDING_MATERIALS = 
SHAPE_SIZE = 2.0
TEXTURE =  grass_fx/highlands.dds  
TEXTURE_GRID = 8, 3 
; trimming grass everywhere
[GRASS_FX_AREA_...]
CENTER = 0, 0
SIZE = 10000, 10000 ; cover everything
MODE = MUL
HEIGHT_MULT = 0.3, 0.8
TRIM_PERIOD = THURSDAY ; grass will be cut each thursday (or, set a number in days to set a period)

[LIGHT_SERIES_0]
DESCRIPTION = street light
ACTIVE=1
MATERIALS = light
ACTIVE = 1
OFFSET = 0,0,0
DIRECTION = 0,-1,0
SPOT = 180
SPOT_SHARPNESS = 0.9
RANGE = 45
RANGE_GRADIENT_OFFSET = 0.4
FADE_AT = 700
FADE_SMOOTH = 30
CLUSTER_THRESHOLD = 12
COLOR = 255, 209, 178, 0.035
SINGLE_FREQUENCY = 0
CONDITION = NIGHT_SMOOTH

[MATERIAL_ADJUSTMENT_0]
ACTIVE = 1
DESCRIPTION = street light
MATERIALS = light
KEY_0 = ksEmissive
VALUE_0 = 255,230,200,0.3
VALUE_0_OFF = 0, 0, 0
KEY_1 = ksAlphaRef
VALUE_1 = -193
VALUE_1_OFF = 0, 0, 0
KEY_2 = ksDiffuse
VALUE_0_OFF = 0.4
CONDITION = NIGHT_SMOOTH
RANGE = 45

[SHADER_REPLACEMENT_...]
DESCRIPTION = double face
ACTIVE = 1 
MATERIALS = light, roada3188, roada3187, roada3302, roada3169, roada3182, roada3168, roada3177, roada3178, roada3180, roada3179, roada3175, roada3171, roada3167, roada3176, roada3173, roada3170, roada3166, roada3172, roada3190, roada2270, roada3323, roada3301, roada2245, roada2242, roada2240, roada1803, roada1802
DOUBLE_FACE_SHADOW_BIASED = 1 
CULL_MODE = DOUBLESIDED 

[SHADER_REPLACEMENT_...]
ACTIVE = 1 
MATERIALS = ?
PROP_... = ksAmbient, 0.5
PROP_... = ksDiffuse, 0.3
PROP_... = ksSpecularEXP, 30
PROP_... = ksSpecular, 0.05

[SHADER_REPLACEMENT_...]
ACTIVE = 1 
MATERIALS = light, roada2307, roada2270, roada2242, roada2271
PROP_... = ksAmbient, 0.2
PROP_... = ksDiffuse, 0.2

[SHADER_REPLACEMENT_...]
ACTIVE = 1 
MATERIALS = roada1705
PROP_... = ksAmbient, 0.35
PROP_... = ksDiffuse, 0.2

[SHADER_REPLACEMENT_...]
ACTIVE = 1 
MATERIALS = roada3302, roada3323, roada3301, roada1473, roada2465, roada3190, roada3278
PROP_... = ksAmbient, 0.8
PROP_... = ksDiffuse, 0.3

[SHADER_REPLACEMENT_...]
ACTIVE = 1 
MATERIALS = roada3188, roada3187
PROP_... = ksAmbient, 0.7

[MESH_ADJUSTMENT_...]
MESHES = skid?
IS_RENDERABLE = 0

[SHADER_REPLACEMENT_...]
ACTIVE = 1 
MATERIALS = NODE
CAST_SHADOWS = 0

[RAIN_FX]
PUDDLES_MATERIALS = roada_tarmac_?, 20 - Default, roada1716
SOAKING_MATERIALS = roada_tarmac_?, 20 - Default
LINES_MATERIALS = roada1705