[ABOUT]
AUTHOR = 
VERSION = 
DATE_RELEASE = 
LIGHTS_COUNT = 
NOTES = 

[SOL]
HORIZON_OFFSET=0.0
DOME_SIZE=20000
SUN_DAWN=1
SUN_DUSK=1
FOG_LEVEL=0.85
FOG_BLEND=1.1
FOG_DISTANCE=1.05
SMOG_MORNING=0.25
SMOG_NOON=0.45
SMOG_EVENING=0.7
EXPOSURE_FIX=1

[LIGHTING]
SPECULAR_MULT = 1
LIT_MULT=1

[DISTANT_GLOW]
THRESHOLD = 25
SHARED_THRESHOLD = 25

[INCLUDE]
INCLUDE = common/conditions.ini, common/materials_track.ini

[LIGHT_POLLUTION]
RELATIVE_POSITION = 33, 0, -18
DENSITY = 1.0
RADIUS_KM = 34.0
COLOR = 1.0, 0.7, 0.4

[LIGHT_SERIES_0]
MATERIALS = Light_rgby
MESHES = 
OFFSET = 0,-0.25,0
CLUSTER_THRESHOLD = 10
COLOR = 212,235,255,0.04
SPOT = 180
RANGE = 100
FADE_AT = 1000
FADE_SMOOTH = 50
SPOT_SHARPNESS = 0.95
DIRECTION = 0,-1,0
RANGE_GRADIENT_OFFSET = 0.01
DIFFUSE_CONCENTRATION = 0.91
ACTIVE = 1
DESCRIPTION = 
SINGLE_FREQUENCY = 0.4
SPECULAR_MULT = 0.25
CONDITION = NIGHT_SMOOTH
SHADOWS_SPOT = 145
SHADOWS_RANGE = 60

[MATERIAL_ADJUSTMENT_0]
MATERIALS = Light_rgby
MESHES = 
CONDITION = NIGHT_SMOOTH
KEY_0 = ksEmissive
VALUE_0 = 212, 235, 255, 0.5
VALUE_0_OFF = 0, 0, 0
ACTIVE = 1
DESCRIPTION = 

[CONDITION_...]
NAME = BLINK
INPUT = ONE
FLASHING_FREQUENCY = 5
FLASHING_SMOOTHNESS = 0
FLASHING_SKIP_OFF_STATE = 0
FLASHING_NOISE_AMPLITUDE = 0
FLASHING_MIN_VALUE = 0.0
FLASHING_SYNCED = 1

[MATERIAL_ADJUSTMENT_...]
ACTIVE = 1
DESCRIPTION = light on
MATERIALS = DIGITALFLAGS, 
KEY_0 = ksEmissive
VALUE_0 = 0,255,0,0.05
VALUE_0_OFF = 0
CONDITION = BLINK

[LIGHT_SERIES_1]
ACTIVE = 1
DESCRIPTION = 
MATERIALS = 
OFFSET = 0,0,0
DIRECTION = 0,-1,0
SPOT = 180
SPOT_SHARPNESS = 0.5
RANGE = 100
RANGE_GRADIENT_OFFSET = 0.4
FADE_AT = 1000
FADE_SMOOTH = 25
COLOR = 200, 200, 200, 0.03
CLUSTER_THRESHOLD = 18
DIFFUSE_CONCENTRATION = 0.5
CONDITION = NIGHT_SMOOTH

[MATERIAL_ADJUSTMENT_1]
ACTIVE = 1
VISIBILITY_LEVEL = 1
DESCRIPTION = 
MATERIALS = 
KEY_0 = ksEmissive
VALUE_0 = 200, 200, 200, 0.3
VALUE_0_OFF = 0, 0, 0
KEY_1 = ksAlphaRef
VALUE_1 = -193
VALUE_1_OFF = 0
CONDITION = NIGHT_SMOOTH

[LIGHT_SERIES_2]
ACTIVE = 1
DESCRIPTION = 
MATERIALS = 
DIRECTION = 0,-1,0
SPOT = 180
SPOT_SHARPNESS = 0.5
RANGE = 60
RANGE_GRADIENT_OFFSET = 0.4
FADE_AT = 1000
FADE_SMOOTH = 25
COLOR = 255, 229, 255, 0.055
CLUSTER_THRESHOLD = 18
DIFFUSE_CONCENTRATION = 0.5
CONDITION = NIGHT_SMOOTH

[MATERIAL_ADJUSTMENT_2]
ACTIVE = 1
VISIBILITY_LEVEL = 1
DESCRIPTION = 
MATERIALS = 
KEY_0 = ksEmissive
VALUE_0 = 255, 229, 255, 0.001
VALUE_0_OFF = 0, 0, 0
KEY_1 = ksAlphaRef
VALUE_1 = -193
VALUE_1_OFF = 0
CONDITION = NIGHT_SMOOTH

[LIGHT_SERIES_3]
ACTIVE = 1
DESCRIPTION = 
MATERIALS = buiildwals, metals_d, ad_board, builds_bgl, gstands22, logo01
OFFSET = 0,0,0
DIRECTION = 0,-1,0
SPOT = 0
SPOT_SHARPNESS = 0.5
RANGE = 10
RANGE_GRADIENT_OFFSET = 0.4
FADE_AT = 400
FADE_SMOOTH = 50
COLOR = 100, 100, 100, 0.05
CLUSTER_THRESHOLD = 18
DIFFUSE_CONCENTRATION = 0.5
CONDITION = NIGHT_SMOOTH

[MATERIAL_ADJUSTMENT_3]
ACTIVE = 1
VISIBILITY_LEVEL = 1
DESCRIPTION = 
MATERIALS = buiildwals, metals_d, ad_board, builds_bgl, Gstand_AT, gstands22, logo01
KEY_0 = ksEmissive
VALUE_0 = 100, 100, 100, 0.0001
VALUE_0_OFF = 0, 0, 0
KEY_1 = ksAlphaRef
VALUE_1 = -193
VALUE_1_OFF = 0
CONDITION = NIGHT_SMOOTH

[LIGHT_SERIES_4]
MATERIALS = windows_glass
OFFSET = -1,1,0
CLUSTER_THRESHOLD = 20
COLOR = 1, 0.71, 0.42,6
SPOT = 140
RANGE = 40
FADE_AT = 400
FADE_SMOOTH = 25
RANGE_GRADIENT_OFFSET = 0.85
SPOT_SHARPNESS = 0.5
DIRECTION = 0,-1,0
CONDITION = INDOORLIGHT
ACTIVE = 1
CONDITION = NIGHT_SMOOTH

[MATERIAL_ADJUSTMENT_4]
ACTIVE = 1
VISIBILITY_LEVEL = 1
DESCRIPTION =
MATERIALS = windows_glass 
KEY_0 = ksEmissive
VALUE_0 = 1, 0.33 , 0.19,16
VALUE_0_OFF = 0.8,0.8,0.8,0.2
ACTIVE = 1
CONDITION = NIGHT_SMOOTH

[Material_RoomWindows]
DebugMode = 0
Meshes = material:windows_glass
EmissiveMode = DIFFUSE_EMISSIVE_BLEND
RoomHeight = 8
RoomVerticalOffset = -3.8
RoomCeilingRotation = 10
RoomCeilingOffset = -0.0, 0.0
RoomCeilingScale = 0.2
RoomNearEdgeClipping = 0.5
RoomDepth = 15
InteriorVolumeBrightness = 1
Shape1_X_W = 0.15
Shape1_Y_W = 0.15
Shape2_X_Mult = 0
ShapeChance = 0.95
ShapeSmoothness = 0.5
NormalsFactor = 0.2                    
InteriorBaseBrightness = 0.5           
InteriorVolumeBrightness = 2.2         
InteriorLightsBrightness = 1.0         
InteriorGlowBrightness = 0.5           
InteriorVolumeAmbientBrightness = 0.5

[SHADER_REPLACEMENT_...]
MATERIALS = windows_glass
CAST_SHADOWS = 1
DOUBLE_FACE_SHADOW_BIASED = 1

[GRASS_FX]
GRASS_MATERIALS = GRASSSIDE, GLASSWORN
OCCLUDING_MATERIALS_ALPHA = 
OCCLUDING_MATERIALS = KERBCURB
ORIGINAL_GRASS_MATERIALS = 
TRIM_PERIOD = THURSDAY
MASK_BLUR = 1
MASK_MAIN_THRESHOLD = 0.75
SHAPE_SIZE = 1.5, 1.25
SHAPE_TIDY = 1, 0.5
SHAPE_CUT = 1, 0
TEXTURE = grass_fx/highlands.dds
TEXTURE_GRID = 8, 3

[GRASS_FX_TEXTURE_GROUP_0]
PIECE_0 = 1, 1
PIECE_1 = 1, 2, 2, 1
PIECE_1_CHANCE = 0.05
PIECE_2 = 4, 1, 2, 2
PIECE_2_CHANCE = 0.75
PIECE_3 = 6, 1
PIECE_4 = 7, 1
PIECE_5 = 8, 1

[GRASS_FX_CONFIGURATION_A]
TEXTURE_BASE_CHANCE = 1
TEXTURE_GROUP_0_CHANCE = 0.125
MASK_MAIN_THRESHOLD = 0.75
TRIM_PERIOD = THURSDAY
SHAPE_SIZE = 1.5, 1.25
SHAPE_TIDY = 1, 0.5
SHAPE_CUT = 1, 0

[GRASS_FX_CONFIGURATION_B]
TEXTURE_BASE_CHANCE = 1
TEXTURE_GROUP_0_CHANCE = 0.125
MASK_MAIN_THRESHOLD = 0.25
TRIM_PERIOD = 30
SHAPE_SIZE = 2.5, 4.0
SHAPE_TIDY = 0.5, 0
SHAPE_CUT = 1, 0

[INCLUDE: common/grass_fx.ini]

[GRASS_FX_ADJUSTMENT_...]
MATERIALS = GRASSSIDE, GLASSWORN
MAP = A

@ = GrassFX_ExtraArea, Map = B, Center = "120, 0, 20", Range = 90, Fade = 55, Aspect = 1.25, Angle = 90
@ = GrassFX_ExtraArea, Map = B, Center = "-35, 0, 130", Range = 90, Fade = 50, Aspect = 1.5, Angle = 40
@ = GrassFX_ExtraArea, Map = B, Center = "-410, 0, -235", Range = 155, Fade = 50, Aspect = 3.5, Angle = -15
@ = GrassFX_ExtraArea, Map = B, Center = "-105, 0, -160", Range = 200, Fade = 50, Aspect = 10, Angle = -17.5
@ = GrassFX_ExtraArea, Map = B, Center = "470, 0, 50", Range = 85, Fade = 50, Aspect = 1.5, Angle = 90
@ = GrassFX_ExtraArea, Map = B, Center = "250, 0, 65", Range = 140, Fade = 50, Aspect = 10, Angle = 2
@ = GrassFX_ExtraArea, Map = B, Center = "-180, 0, -40", Range = 160, Fade = 50, Aspect = 1.65, Angle = -20

[Material_Water]
Materials = WATER01
Type = POND
UseNormalMapTwice = 1
UseAlphaFromDiffuse = 0
UseRecommendedTextures = 0

[MESH_ADJUSTMENT_0_WATERFIX]
MESHES = material:water01
IS_TRANSPARENT = 1

[MATERIAL_ADJUSTMENT_0_WATERFIX]
MESHES = material:water01
;DEPTH_MODE = NORMAL
BLEND_MODE = ALPHA_BLEND

[Material_DistantEmissive]
MATERIALS = Light_rgby
Meshes = 
FloodlightPower = 2
FloodlightEXP = 5.0
DistanceMult_v2 = 0.0

[Material_DistantEmissive]
Meshes = 1PITS_SUB02
FloodlightPower = 2
FloodlightEXP = 5.0
DotRadiusMult_v2 = 5.0
DistanceMult_v2 = 0.2
DistantGlowRadius_v2 = 1.5

[Material_DistantEmissive]
Meshes = 
DistantGlowMult_v2 = 2.0
DotRadiusMult_v2 = 0.0
DistanceMult_v2 = 0.0
DistantGlowHeightMult_v2 = 0.5
DistantGlowRadius_v2 = 1.25

[Material_RoomWindows]
Materials = window07
EmissiveMode = DIFFUSE_TEXTURE
SnapToTexCoords = 1
TexCoordsSnapOffset = 1.0
NormalsFactor = 0
RoomCeilingScale = 0.5
RoomCeilingRotation = 73.0
RoomDepth = 4.5
ShapeChance = 1
Shape1_X_W = 0.01
Shape1_Y_W = 0.01
ShapeSmoothness = 0.85
InteriorBaseBrightness = 2.5
InteriorMult = 1.0
InteriorGlowBrightness = 1
InteriorVolumeBrightness = 5
InteriorLightsBrightness = 1.25

[Material_RoomWindows]
Materials = DOOR_CAR
EmissiveMode = DIFFUSE_TEXTURE
RoomHeight = 3.2
RoomVerticalOffset = 0.1
NormalsFactor = 0
RoomCeilingScale = 0.6
RoomCeilingRotation = 73.0
RoomCeilingOffset = 2.5, 1
RoomDepth = 5.5
ShapeChance = 0.65
Shape1_X_W = 0.1
Shape1_Y_W = 0.1
ShapeSmoothness = 0.35
InteriorVolumeBrightness = 10
InteriorGlowBrightness = 1.5
InteriorLightsBrightness = 10
InteriorBaseBrightness = 2.5

[Material_RoomWindows]
Materials = 
EmissiveMode = DIFFUSE_TEXTURE
RoomHeight = 3.5
RoomVerticalOffset = 1.5
NormalsFactor = 0
RoomCeilingScale = 0.4
RoomCeilingRotation = 73.0
RoomCeilingOffset = 2.5, 1
RoomDepth = 5.5
ShapeChance = 0.7
Shape1_X_W = 0.1
Shape1_Y_W = 0.4
ShapeSmoothness = 0.35
InteriorVolumeBrightness = 10
InteriorGlowBrightness = 1.5
InteriorLightsBrightness = 10
InteriorBaseBrightness = 2.5

[BOUNCED_LIGHT]
SUPPORTED = 1
INTENSITY = 0.6
SURFACE_MATERIALS = SPLINE01, PITLINE, roadd01, trrainmask

[SHADER_REPLACEMENT_...]
ACTIVE = 1
MESHES = 
MATERIALS = neiqiang01, DOOR_CAR, 1Buindling_6_002, adborad2
CAST_SHADOWS = 1
DOUBLE_FACE_SHADOW_BIASED = 1

[RAIN_FX]
PUDDLES_MATERIALS = roadasph4, SANDS, road_dm, PITLINE, START_YLINE, KERBCURB
SOAKING_MATERIALS = 
SMOOTH_MATERIALS = 
ROUGH_MATERIALS = 