; Toprace URL: http://www.toprace.top

[ABOUT]
AUTHOR = BUG3721
VERSION = v1.0
DATE_RELEASE = 19-10-20
LIGHTS_COUNT = 
NOTES = 

[LIGHTING]
SPECULAR_MULT = 1
LIT_MULT=1

[WIND]
DYNAMIC_FLAGS = AUTO

[INCLUDE]
INCLUDE = common/conditions.ini, common/materials_track.ini

[LIGHT_SERIES_1]
ACTIVE = 1
DESCRIPTION = 
MATERIALS = Light_rgby
OFFSET = 0,0,0
DIRECTION = 0,-1,0
SPOT = 180
SPOT_SHARPNESS = 0.5
RANGE = 100
RANGE_GRADIENT_OFFSET = 0.4
FADE_AT = 1000
FADE_SMOOTH = 25
COLOR = 255, 229, 255, 0.04
CLUSTER_THRESHOLD = 18
DIFFUSE_CONCENTRATION = 0.5
CONDITION = NIGHT_SMOOTH

[MATERIAL_ADJUSTMENT_1]
ACTIVE = 1
VISIBILITY_LEVEL = 1
DESCRIPTION = 
MATERIALS = Light_rgby
KEY_0 = ksEmissive
VALUE_0 = 255, 229, 255, 0.05
VALUE_0_OFF = 0, 0, 0
KEY_1 = ksAlphaRef
VALUE_1 = -193
VALUE_1_OFF = 0
CONDITION = NIGHT_SMOOTH

[LIGHT_SERIES_2]
ACTIVE = 1
DESCRIPTION = 
MATERIALS = Gstand_AT
DIRECTION = 0,-1,0
SPOT = 180
SPOT_SHARPNESS = 0.5
RANGE = 60
RANGE_GRADIENT_OFFSET = 0.4
FADE_AT = 1000
FADE_SMOOTH = 25
COLOR = 255, 229, 255, 0.055
CLUSTER_THRESHOLD = 18
DIFFUSE_CONCENTRATION = 0.5
CONDITION = NIGHT_SMOOTH

[MATERIAL_ADJUSTMENT_2]
ACTIVE = 1
VISIBILITY_LEVEL = 1
DESCRIPTION = 
MATERIALS = 
KEY_0 = ksEmissive
VALUE_0 = 255, 229, 255, 0.001
VALUE_0_OFF = 0, 0, 0
KEY_1 = ksAlphaRef
VALUE_1 = -193
VALUE_1_OFF = 0
CONDITION = NIGHT_SMOOTH

[LIGHT_SERIES_3]
ACTIVE = 1
DESCRIPTION = 
MATERIALS = SGSTEEL, gstands_alpha, startlight, rhc, misc, glassblue
OFFSET = 0,0,0
DIRECTION = 0,-1,0
SPOT = 180
SPOT_SHARPNESS = 0.5
RANGE = 40
RANGE_GRADIENT_OFFSET = 0.4
FADE_AT = 1000
FADE_SMOOTH = 25
COLOR = 255, 229, 255, 0.05
CLUSTER_THRESHOLD = 18
DIFFUSE_CONCENTRATION = 0.5
CONDITION = NIGHT_SMOOTH

[MATERIAL_ADJUSTMENT_3]
ACTIVE = 1
VISIBILITY_LEVEL = 1
DESCRIPTION = 
MATERIALS = SGSTEEL, gstands_alpha, startlight, rhc, misc, glassblue
KEY_0 = ksEmissive
VALUE_0 = 255, 229, 255, 0.0001
VALUE_0_OFF = 0, 0, 0
KEY_1 = ksAlphaRef
VALUE_1 = -193
VALUE_1_OFF = 0
CONDITION = NIGHT_SMOOTH

[LIGHT_...]
COLOR_FROM=0.5, 1, 0.866397, 20.5
COLOR_TO=1, 1, 0.5, 10
DIFFUSE_CONCENTRATION=1.000
FADE_AT=448.8
FADE_SMOOTH=140.3
LINE_FROM=75.5798, 0.476163, -281.29
LINE_TO=70.9287, 0.993942, -349.553
RANGE=25.40
RANGE_GRADIENT_OFFSET=0.100
SINGLE_FREQUENCY=0.000
SPECULAR_MULT=1.00
SPOT=0.00

[LIGHT_...]
COLOR_FROM=0.9999, 1, 0.999973, 20.5
COLOR_TO=1, 1, 0.9999, 10
DIFFUSE_CONCENTRATION=1.000
FADE_AT=448.8
FADE_SMOOTH=140.3
LINE_FROM=236.845, 8.54044, -62.6982
LINE_TO=203.237, 7.92845, -67.4761
RANGE=12.80
RANGE_GRADIENT_OFFSET=0.100
SINGLE_FREQUENCY=0.000
SPECULAR_MULT=1.00
SPOT=0.00

[LIGHT_...]
COLOR_FROM=1, 1, 0.9999, 21.4
COLOR_TO=1, 1, 0.9999, 10
DIFFUSE_CONCENTRATION=1.000
FADE_AT=353.6
FADE_SMOOTH=127.1
LINE_FROM=-34.1572, -1.53851, -392.597
LINE_TO=-2.63612, -1.2518, -398.041
RANGE=4.80
RANGE_GRADIENT_OFFSET=0.670
SINGLE_FREQUENCY=0.570
SPECULAR_MULT=0.00
SPOT=0.00

[LIGHT_...]
COLOR_FROM=1, 1, 0.9999, 15.1
COLOR_TO=1, 1, 0.9999, 10
DIFFUSE_CONCENTRATION=1.000
FADE_AT=353.6
FADE_SMOOTH=127.1
LINE_FROM=-6.19325, -0.799977, -394.386
LINE_TO=-29.0508, -1.01314, -389.273
RANGE=4.00
RANGE_GRADIENT_OFFSET=0.670
SINGLE_FREQUENCY=0.570
SPECULAR_MULT=0.00
SPOT=0.00

[GRASS_FX]
GRASS_MATERIALS = GRASS01, grass8
GRASS_MESHES = 
OCCLUDING_MESHES = 
OCCLUDING_MATERIALS = 
OCCLUDING_MATERIALS_ALPHA = kerb01
ORIGINAL_GRASS_MATERIALS= 
MASK_BLUR = 1
SHAPE_SIZE = 4.5, 1.0   
SHAPE_TIDY = 0.0   
SHAPE_CUT = 0.0    
SHAPE_WIDTH = 1.0
TRIM_PERIOD = 365 
MASK_MAIN_THRESHOLD = 0.5
MASK_RED_THRESHOLD = 0.05
MASK_MIN_LUMINANCE = 0.02
MASK_MAX_LUMINANCE = 1.0
TEXTURE = grass_fx/highlands.dds
TEXTURE_GRID = 8, 3

[GRASS_FX_TEXTURE_GROUP_0]
PIECE_0 = 1, 1
PIECE_0_CHANCE = 0.25
PIECE_1 = 1, 2, 2, 1
PIECE_1_CHANCE = 0.05
PIECE_2 = 4, 1, 2, 2
PIECE_2_CHANCE = 0.5
PIECE_3 = 6, 1
PIECE_4 = 7, 1
PIECE_5 = 8, 1

[GRASS_FX_CONFIGURATION_A]
SHAPE_SIZE = 1.0, 3.5
SHAPE_CUT = 1, 0
SHAPE_TIDY = 1, 0.5
TRIM_PERIOD = 30
MASK_MAIN_THRESHOLD = 0.6
MASK_MAX_LUMINANCE = 0.1
TEXTURE_BASE_CHANCE = 1
TEXTURE_GROUP_0_CHANCE = 0.2

[GRASS_FX_CONFIGURATION_B]
SHAPE_SIZE = 3.5, 6.0
SHAPE_CUT = 0
SHAPE_TIDY = 0
TRIM_PERIOD = 365
MASK_MAIN_THRESHOLD = 0.4
MASK_MAX_LUMINANCE = 0.105
TEXTURE_BASE_CHANCE = 1
TEXTURE_GROUP_0_CHANCE = 0.5

[GRASS_FX_ADJUSTMENT_...]
MATERIALS = 
MAP = A

[GRASS_FX_ADJUSTMENT_...]
MATERIALS = 
MAP = B

[RAIN_FX]
PUDDLES_MATERIALS = road01, PITLINE, LINECOLOR01, roadout01, CURBGRASS1, kerb01
SOAKING_MATERIALS = 
SMOOTH_MATERIALS = 
ROUGH_MATERIALS = 
