; Toprace URL: http://www.toprace.top

[ABOUT]
AUTHOR = BUG3721
VERSION = v1.1
DATE_RELEASE = 01-01-21
LIGHTS_COUNT = 
NOTES = 

[SOL]
HORIZON_OFFSET = 0.0
DOME_SIZE = 20000
SUN_DAWN = 1
SUN_DUSK = 1
FOG_LEVEL = 0.90
FOG_BLEND = 1.15
FOG_DISTANCE = 0.9
SMOG_MORNING = 0.05
SMOG_NOON = 0.1
SMOG_EVENING = 0.15
EXPOSURE_FIX = 1

[LIGHTING]
SPECULAR_MULT = 1
LIT_MULT=1

[WIND]
DYNAMIC_FLAGS = AUTO

[INCLUDE]
INCLUDE = common/conditions.ini, common/materials_track.ini

[LIGHT_POLLUTION]
RELATIVE_POSITION = 33, 0, -18
DENSITY = 1.0
RADIUS_KM = 34.0
COLOR = 1.0, 0.7, 0.4

[LIGHT_SERIES_0]
ACTIVE=1
VISIBILITY_LEVEL=0
DESCRIPTION=
MATERIALS=
OFFSET=0,0,0
DIRECTION=DIRECTION=0,-1,0
SPOT=180
SPOT_SHARPNESS=0.76
RANGE=70
RANGE_GRADIENT_OFFSET=0.4
FADE_AT=1000
FADE_SMOOTH=40
CLUSTER_THRESHOLD=30
SINGLE_FREQUENCY=0.5
COLOR=234,121,36,0.05
COLOR_OFF=255,183,76,0
CONDITION=NIGHT_SMOOTH

[MATERIAL_ADJUSTMENT_0]
ACTIVE=1
VISIBILITY_LEVEL=0
DESCRIPTION=
MATERIALS=GLASS11PAD, GLASSABC, GLASSKARTKC 
KEY_0=ksEmissive
VALUE_0=234,121,36,0.01
VALUE_0_OFF=0, 0, 0
KEY_1=ksAlphaRef
VALUE_1=-193
VALUE_1_OFF=0, 0, 0
CONDITION=NIGHT_SMOOTH

[LIGHT_SERIES_1]
MATERIALS = Material #1118 
OFFSET = 0,0,0
CLUSTER_THRESHOLD = 30
COLOR = 234, 201, 181, 0.05
SPOT = 180
RANGE = 100
RANGE_GRADIENT_OFFSET = 0.4
FADE_AT = 1000
FADE_SMOOTH = 50
DIRECTION = NORMAL
DIFFUSE_CONCENTRATION = 1
ACTIVE = 1
CONDITION = NIGHT_SMOOTH

[MATERIAL_ADJUSTMENT_1]
MATERIALS = Material #1118
KEY_0 = ksEmissive
VALUE_0 = 234, 201, 181, 0.5
VALUE_0_OFF = 0, 0, 0
ACTIVE = 1
CONDITION = NIGHT_SMOOTH

[LIGHT_SERIES_2]
ACTIVE = 1
DESCRIPTION = 
MATERIALS = 
DIRECTION = 0,-1,0
SPOT = 180
SPOT_SHARPNESS = 0.5
RANGE = 100
RANGE_GRADIENT_OFFSET = 0.4
FADE_AT = 1000
FADE_SMOOTH = 25
COLOR = 234, 201, 255, 0.055
CLUSTER_THRESHOLD = 18
DIFFUSE_CONCENTRATION = 0.5
CONDITION = NIGHT_SMOOTH

[MATERIAL_ADJUSTMENT_2]
ACTIVE = 1
VISIBILITY_LEVEL = 1
DESCRIPTION = 
MATERIALS = 
KEY_0 = ksEmissive
VALUE_0 = 255, 229, 255, 0.05
VALUE_0_OFF = 0, 0, 0
KEY_1 = ksAlphaRef
VALUE_1 = -193
VALUE_1_OFF = 0
CONDITION = NIGHT_SMOOTH

[LIGHT_SERIES_3]
ACTIVE = 1
DESCRIPTION = 
MATERIALS = 
OFFSET = 0,0,0
DIRECTION = 0,-0.1,0
SPOT = 180
SPOT_SHARPNESS = 0.5
RANGE = 40
RANGE_GRADIENT_OFFSET = 0.4
FADE_AT = 1000
FADE_SMOOTH = 25
COLOR = 255, 229, 255, 0.04
CLUSTER_THRESHOLD = 18
DIFFUSE_CONCENTRATION = 0.5
CONDITION = NIGHT_SMOOTH

[MATERIAL_ADJUSTMENT_3]
ACTIVE = 1
VISIBILITY_LEVEL = 1
DESCRIPTION = 
MATERIALS = 
KEY_0 = ksEmissive
VALUE_0 = 255, 229, 255, 0.003
VALUE_0_OFF = 0, 0, 0
KEY_1 = ksAlphaRef
VALUE_1 = -193
VALUE_1_OFF = 0
CONDITION = NIGHT_SMOOTH

[LIGHT_SERIES_4]
ACTIVE = 1
DESCRIPTION = 
MATERIALS = 
OFFSET = 0,0,0
DIRECTION = 0,-1,0
SPOT = 180
SPOT_SHARPNESS = 0.5
RANGE = 80
RANGE_GRADIENT_OFFSET = 0.4
FADE_AT = 1000
FADE_SMOOTH = 25
COLOR = 234, 182, 146, 0.05
CLUSTER_THRESHOLD = 18
DIFFUSE_CONCENTRATION = 0.5
CONDITION = NIGHT_SMOOTH

[MATERIAL_ADJUSTMENT_4]
ACTIVE = 1
VISIBILITY_LEVEL = 1
DESCRIPTION = 
MATERIALS = 
KEY_0 = ksEmissive
VALUE_0 = 234, 182, 146, 0.3
VALUE_0_OFF = 0, 0, 0
KEY_1 = ksAlphaRef
VALUE_1 = -193
VALUE_1_OFF = 0
CONDITION = NIGHT_SMOOTH

[LIGHT_SERIES_5]
ACTIVE = 1
DESCRIPTION = 
MATERIALS = 
OFFSET = 0,0,0
DIRECTION = 0,-1,0
SPOT = 180
SPOT_SHARPNESS = 0.5
RANGE = 80
RANGE_GRADIENT_OFFSET = 0.4
FADE_AT = 1000
FADE_SMOOTH = 25
COLOR = 234, 201, 181, 0.05
CLUSTER_THRESHOLD = 18
DIFFUSE_CONCENTRATION = 0.5
CONDITION = NIGHT_SMOOTH

[MATERIAL_ADJUSTMENT_5]
ACTIVE = 1
VISIBILITY_LEVEL = 1
DESCRIPTION = 
MATERIALS = 
KEY_0 = ksEmissive
VALUE_0 = 234, 201, 181, 0.3
VALUE_0_OFF = 0, 0, 0
KEY_1 = ksAlphaRef
VALUE_1 = -193
VALUE_1_OFF = 0
CONDITION = NIGHT_SMOOTH

[LIGHT_SERIES_6]
ACTIVE = 1
DESCRIPTION = standard_2
MATERIALS = 
OFFSET = 0,0,0
DIRECTION = 0,0,0
SPOT = 180
SPOT_SHARPNESS = 0.5
RANGE = 50
RANGE_GRADIENT_OFFSET = 0.4
FADE_AT = 1000
FADE_SMOOTH = 25
COLOR = 255, 229, 255, 0.02
CLUSTER_THRESHOLD = 18
DIFFUSE_CONCENTRATION = 0.5
CONDITION = NIGHT_SMOOTH

[MATERIAL_ADJUSTMENT_6]
ACTIVE = 1
VISIBILITY_LEVEL = 1
DESCRIPTION = 
MATERIALS = 
KEY_0 = ksEmissive
VALUE_0 = 255, 229, 255, 0.0004
VALUE_0_OFF = 0, 0, 0
KEY_1 = ksAlphaRef
VALUE_1 = -193
VALUE_1_OFF = 0
CONDITION = NIGHT_SMOOTH

[LIGHT_SERIES_7]
ACTIVE = 1
DESCRIPTION = 
MATERIALS = 
OFFSET = 0,0,0
DIRECTION = 0,-0.9,0
SPOT = 180
SPOT_SHARPNESS = 0.5
RANGE = 40
RANGE_GRADIENT_OFFSET = 0.4
FADE_AT = 1000
FADE_SMOOTH = 25
COLOR = 255, 229, 255, 0.02
CLUSTER_THRESHOLD = 18
DIFFUSE_CONCENTRATION = 0.5
CONDITION = NIGHT_SMOOTH

[MATERIAL_ADJUSTMENT_7]
ACTIVE = 1
VISIBILITY_LEVEL = 1
DESCRIPTION = 
MATERIALS = 
KEY_0 = ksEmissive
VALUE_0 = 255, 229, 255, 0.0008
VALUE_0_OFF = 0, 0, 0
KEY_1 = ksAlphaRef
VALUE_1 = -193
VALUE_1_OFF = 0
CONDITION = NIGHT_SMOOTH

[LIGHT_SERIES_8]
ACTIVE = 1
DESCRIPTION = 
MATERIALS = 
OFFSET = 0,0,0
DIRECTION = 0,-0.1,0
SPOT = 150
SPOT_SHARPNESS = 0.5
RANGE = 40
RANGE_GRADIENT_OFFSET = 0.4
FADE_AT = 1000
FADE_SMOOTH = 25
COLOR = 255, 229, 255, 0.05
CLUSTER_THRESHOLD = 18
DIFFUSE_CONCENTRATION = 0.5
CONDITION = NIGHT_SMOOTH

[MATERIAL_ADJUSTMENT_8]
ACTIVE = 1
VISIBILITY_LEVEL = 1
DESCRIPTION = 
MATERIALS = 
KEY_0 = ksEmissive
VALUE_0 = 255, 229, 255, 0.002
VALUE_0_OFF = 0, 0, 0
KEY_1 = ksAlphaRef
VALUE_1 = -193
VALUE_1_OFF = 0
CONDITION = NIGHT_SMOOTH

[Material_Water]
Materials = 
UseAlphaFromNormal = 1
UseRecommendedTextures = 0
UseRecommendedDetailTexture = 1
UseNormalMapTwice = 1
Type = POND

[GRASS_FX]
GRASS_MATERIALS = Material #2291
GRASS_MESHES = 
OCCLUDING_MESHES = 
OCCLUDING_MATERIALS = 
OCCLUDING_MATERIALS_ALPHA = Material #1186
ORIGINAL_GRASS_MATERIALS= Material #2292
MASK_BLUR = 1
SHAPE_SIZE = 4.5, 2.0   
SHAPE_TIDY = 0.0   
SHAPE_CUT = 0.0    
SHAPE_WIDTH = 1.0
TRIM_PERIOD = 365 
MASK_MAIN_THRESHOLD = 0.5
MASK_RED_THRESHOLD = 0.05
MASK_MIN_LUMINANCE = 0.001
MASK_MAX_LUMINANCE = 0.5
TEXTURE =  grass_fx/highlands.dds
TEXTURE_GRID =8, 3

[GRASS_FX_TEXTURE_GROUP_0]
PIECE_0 = 1, 1
PIECE_0_CHANCE = 0.25
PIECE_1 = 1, 2, 2, 1
PIECE_1_CHANCE = 0.05
PIECE_2 = 4, 1, 2, 2
PIECE_2_CHANCE = 0.5
PIECE_3 = 6, 1
PIECE_4 = 7, 1
PIECE_5 = 8, 1

[GRASS_FX_CONFIGURATION_A]
SHAPE_SIZE = 1.0, 3.5
SHAPE_CUT = 1, 0
SHAPE_TIDY = 1, 0.5
TRIM_PERIOD = 30
MASK_MAIN_THRESHOLD = 0.6
MASK_MAX_LUMINANCE = 0.1
TEXTURE_BASE_CHANCE = 1
TEXTURE_GROUP_0_CHANCE = 0.2

[GRASS_FX_CONFIGURATION_B]
SHAPE_SIZE = 3.5, 6.0
SHAPE_CUT = 0
SHAPE_TIDY = 0
TRIM_PERIOD = 365
MASK_MAIN_THRESHOLD = 0.4
MASK_MAX_LUMINANCE = 0.105
TEXTURE_BASE_CHANCE = 1
TEXTURE_GROUP_0_CHANCE = 0.5

[GRASS_FX_ADJUSTMENT_...]
MATERIALS = 
MAP = A

[GRASS_FX_ADJUSTMENT_...]
MATERIALS = Material #2291
MAP = B

[RAIN_FX]
PUDDLES_MATERIALS = 1ROAD01, Material #29
SOAKING_MATERIALS = 
SMOOTH_MATERIALS = 
ROUGH_MATERIALS = 
