; Toprace URL: http://www.trmod.top

[ABOUT]
AUTHOR = BUG3721
VERSION = v1.6
DATE_RELEASE = 27-04-22
LIGHTS_COUNT = 
NOTES = 

[SOL]
HORIZON_OFFSET = 0.0
DOME_SIZE = 20000
SUN_DAWN = 1
SUN_DUSK = 1
FOG_LEVEL = 0.90
FOG_BLEND = 1.15
FOG_DISTANCE = 0.9
SMOG_MORNING = 0.05
SMOG_NOON = 0.1
SMOG_EVENING = 0.15
EXPOSURE_FIX = 1

[LIGHTING]
SPECULAR_MULT=1.0
LIT_MULT=1.0

[WIND]
DYNAMIC_FLAGS = AUTO

[INCLUDE]
INCLUDE = common/conditions.ini, common/materials_track.ini

[SOUNDBANK_0]
BANK = sfx/tr_shanghai.bank
GUIDS = sfx/GUIDs.txt

[EVENT_0]
ID = racetrack/Helicopter
REVERB_RESPONSE = 1
VOLUME = 1.0
CAMERA_INTERIOR_MULT = 1.0
CAMERA_EXTERIOR_MULT = 1.0
CAMERA_TRACK_MULT = 1.0
RELATIVE_TO = helicopter_01
POSITION = 0, 0, 0
DIRECTION = 1, 1, 1
 
[EVENT_1]
ID = racetrack/Helicopter
REVERB_RESPONSE = 1
VOLUME = 1.0
CAMERA_INTERIOR_MULT = 1.0
CAMERA_EXTERIOR_MULT = 1.0
CAMERA_TRACK_MULT = 1.0
RELATIVE_TO = helicopter_02
POSITION = 0.0, 0.0, 0.0
DIRECTION = 1, 1, 1
 
[EVENT_2]
ID = racetrack/Helicopter
REVERB_RESPONSE = 1
VOLUME = 1.0
CAMERA_INTERIOR_MULT = 1.0
CAMERA_EXTERIOR_MULT = 1.0
CAMERA_TRACK_MULT = 1.0
RELATIVE_TO = helicopter_03
POSITION = 0.0, 0.0, 0.0
DIRECTION = 1, 1, 1
 
[EVENT_3]
ID = racetrack/Helicopter
REVERB_RESPONSE = 1
VOLUME = 1.0
CAMERA_INTERIOR_MULT = 1.0
CAMERA_EXTERIOR_MULT = 1.0
CAMERA_TRACK_MULT = 1.0
RELATIVE_TO = helicopter_04
POSITION = 0.0, 0.0, 0.0
DIRECTION = 1, 1, 1

[EVENT_4]
ID = racetrack/Planeprop
REVERB_RESPONSE = 0
VOLUME = 1.0
CAMERA_INTERIOR_MULT = 1
CAMERA_EXTERIOR_MULT = 1.0
CAMERA_TRACK_MULT = 1.0
RELATIVE_TO = airship
POSITION = 0.0, 0.0, 0.0
DIRECTION = 1, 1, 1

[LIGHT_SERIES_0]
ACTIVE=1
VISIBILITY_LEVEL=0
DESCRIPTION=
MATERIALS= fire
OFFSET=0,0,0
DIRECTION=DIRECTION=0,-1,0
SPOT=180
SPOT_SHARPNESS=0.76
RANGE=40
RANGE_GRADIENT_OFFSET=0.4
FADE_AT=1000
FADE_SMOOTH=40
CLUSTER_THRESHOLD=30
SINGLE_FREQUENCY=0.5
COLOR=200,60,35,0.5
COLOR_OFF=255,183,76,0
CONDITION=NIGHT_SMOOTH

[MATERIAL_ADJUSTMENT_0]
ACTIVE=1
VISIBILITY_LEVEL=0
DESCRIPTION=
MATERIALS= fire
KEY_0=ksEmissive
VALUE_0=234,121,36,0.5
VALUE_0_OFF=0, 0, 0
KEY_1=ksAlphaRef
VALUE_1=-193
VALUE_1_OFF=0, 0, 0
CONDITION=NIGHT_SMOOTH

[LIGHT_SERIES_1]
MATERIALS = light_b
OFFSET = 0,0,0
CLUSTER_THRESHOLD = 30
COLOR = 255, 229, 255, 0.03
SPOT = 180
RANGE = 125
RANGE_GRADIENT_OFFSET = 0.4
FADE_AT = 1000
FADE_SMOOTH = 50
DIRECTION = NORMAL
DIFFUSE_CONCENTRATION = 1
ACTIVE = 1
CONDITION = NIGHT_SMOOTH

[MATERIAL_ADJUSTMENT_1]
MATERIALS = light_b
KEY_0 = ksEmissive
VALUE_0 = 255, 229, 255, 1.0
VALUE_0_OFF = 0, 0, 0
ACTIVE = 1
CONDITION = NIGHT_SMOOTH

[LIGHT_SERIES_2]
ACTIVE = 1
DESCRIPTION = 
MATERIALS = 
DIRECTION = 0,-1,0
SPOT = 180
SPOT_SHARPNESS = 0.5
RANGE = 100
RANGE_GRADIENT_OFFSET = 0.4
FADE_AT = 1000
FADE_SMOOTH = 25
COLOR = 255, 229, 255, 0.04
CLUSTER_THRESHOLD = 18
DIFFUSE_CONCENTRATION = 0.5
CONDITION = NIGHT_SMOOTH

[MATERIAL_ADJUSTMENT_2]
ACTIVE = 1
VISIBILITY_LEVEL = 1
DESCRIPTION = 
MATERIALS = 
KEY_0 = ksEmissive
VALUE_0 = 255, 229, 255, 0.04
VALUE_0_OFF = 0, 0, 0
KEY_1 = ksAlphaRef
VALUE_1 = -193
VALUE_1_OFF = 0
CONDITION = NIGHT_SMOOTH

[LIGHT_SERIES_3]
ACTIVE = 1
DESCRIPTION = 
MATERIALS = tr_skybridge_c_01, tr_skybridge_b_01
OFFSET = 0,0,0
DIRECTION = 0,-0.1,0
SPOT = 180
SPOT_SHARPNESS = 0.5
RANGE = 40
RANGE_GRADIENT_OFFSET = 0.4
FADE_AT = 1000
FADE_SMOOTH = 25
COLOR = 255, 229, 255, 0.02
CLUSTER_THRESHOLD = 18
DIFFUSE_CONCENTRATION = 0.5
CONDITION = NIGHT_SMOOTH

[MATERIAL_ADJUSTMENT_3]
ACTIVE = 1
VISIBILITY_LEVEL = 1
DESCRIPTION = 
MATERIALS = tr_skybridge_c_01, tr_skybridge_b_01
KEY_0 = ksEmissive
VALUE_0 = 255, 229, 255, 0.003
VALUE_0_OFF = 0, 0, 0
KEY_1 = ksAlphaRef
VALUE_1 = -193
VALUE_1_OFF = 0
CONDITION = NIGHT_SMOOTH

[LIGHT_SERIES_4]
ACTIVE = 1
DESCRIPTION = 
MATERIALS = mainlight_b
OFFSET = 0,0,0
DIRECTION = 0,-1,0
SPOT = 180
SPOT_SHARPNESS = 0.5
RANGE = 110
RANGE_GRADIENT_OFFSET = 0.4
FADE_AT = 1000
FADE_SMOOTH = 25
COLOR = 255, 229, 255, 0.02
CLUSTER_THRESHOLD = 18
DIFFUSE_CONCENTRATION = 0.5
CONDITION = NIGHT_SMOOTH

[MATERIAL_ADJUSTMENT_4]
ACTIVE = 1
VISIBILITY_LEVEL = 1
DESCRIPTION = 
MATERIALS = mainlight_b
KEY_0 = ksEmissive
VALUE_0 = 255, 229, 255, 1.0
VALUE_0_OFF = 0, 0, 0
KEY_1 = ksAlphaRef
VALUE_1 = -193
VALUE_1_OFF = 0
CONDITION = NIGHT_SMOOTH

[LIGHT_SERIES_5]
ACTIVE = 1
DESCRIPTION = 
MATERIALS = Schermo_2, schermo_3
OFFSET = 0,0,0
DIRECTION = 0,-1,0
SPOT = 180
SPOT_SHARPNESS = 0.5
RANGE = 180
RANGE_GRADIENT_OFFSET = 0.4
FADE_AT = 1000
FADE_SMOOTH = 25
COLOR = 255, 229, 255, 0.01
CLUSTER_THRESHOLD = 18
DIFFUSE_CONCENTRATION = 0.5
CONDITION = NIGHT_SMOOTH

[MATERIAL_ADJUSTMENT_5]
ACTIVE = 1
VISIBILITY_LEVEL = 1
DESCRIPTION = 
MATERIALS = Schermo_2, schermo_3, Rotor
KEY_0 = ksEmissive
VALUE_0 = 255, 229, 255, 0.008
VALUE_0_OFF = 0, 0, 0
KEY_1 = ksAlphaRef
VALUE_1 = -193
VALUE_1_OFF = 0
CONDITION = NIGHT_SMOOTH

[LIGHT_SERIES_6]
ACTIVE = 1
DESCRIPTION = 
MATERIALS = 
OFFSET = 0,0,0
DIRECTION = 0,0,0
SPOT = 180
SPOT_SHARPNESS = 0.5
RANGE = 50
RANGE_GRADIENT_OFFSET = 0.4
FADE_AT = 1000
FADE_SMOOTH = 25
COLOR = 255, 229, 255, 0.02
CLUSTER_THRESHOLD = 18
DIFFUSE_CONCENTRATION = 0.5
CONDITION = NIGHT_SMOOTH

[MATERIAL_ADJUSTMENT_6]
ACTIVE = 1
VISIBILITY_LEVEL = 1
DESCRIPTION = 
MATERIALS = tr_grandstand_main_aa_01, tr_glasstower_b_01, tr_pitgarages_aa_02b, tr_pitgarages_aa_03, tr_glasstower_a_01, tr_pitgarages_ad_03, tr_infrastructure_brollyroof_b_02, tr_infrastructure_brollyroof_b_01, tr_commstower_a_01, tr_kartcenter_a_01, tr_commsplex_a_01, tr_publicwc_a_01, tr_infrastructure_pylon_a_01, tr_building_a_01, tr_building_b_01, tr_building_c_01
VALUE_0 = 255, 229, 255, 0.0004
VALUE_0_OFF = 0, 0, 0
KEY_1 = ksAlphaRef
VALUE_1 = -193
VALUE_1_OFF = 0
CONDITION = NIGHT_SMOOTH

[LIGHT_SERIES_7]
ACTIVE = 1
DESCRIPTION = 
MATERIALS = CoastGuardHelicopter_Glass, CoastGuardHelicopter, 
OFFSET = 0,0,0
DIRECTION = 0,-0.9,0
SPOT = 180
SPOT_SHARPNESS = 0.5
RANGE = 40
RANGE_GRADIENT_OFFSET = 0.4
FADE_AT = 1000
FADE_SMOOTH = 25
COLOR = 255, 229, 255, 0.02
CLUSTER_THRESHOLD = 18
DIFFUSE_CONCENTRATION = 0.5
CONDITION = NIGHT_SMOOTH

[MATERIAL_ADJUSTMENT_7]
ACTIVE = 1
VISIBILITY_LEVEL = 1
DESCRIPTION = 
MATERIALS = CoastGuardHelicopter_Glass, CoastGuardHelicopter, 
KEY_0 = ksEmissive
VALUE_0 = 255, 229, 255, 0.0008
VALUE_0_OFF = 0, 0, 0
KEY_1 = ksAlphaRef
VALUE_1 = -193
VALUE_1_OFF = 0
CONDITION = NIGHT_SMOOTH

[LIGHT_SERIES_8]
ACTIVE = 1
DESCRIPTION = 
MATERIALS = 
OFFSET = 0,0,0
DIRECTION = 0,-0.1,0
SPOT = 150
SPOT_SHARPNESS = 0.5
RANGE = 40
RANGE_GRADIENT_OFFSET = 0.4
FADE_AT = 1000
FADE_SMOOTH = 25
COLOR = 255, 229, 255, 0.05
CLUSTER_THRESHOLD = 18
DIFFUSE_CONCENTRATION = 0.5
CONDITION = NIGHT_SMOOTH

[MATERIAL_ADJUSTMENT_8]
ACTIVE = 1
VISIBILITY_LEVEL = 1
DESCRIPTION = 
MATERIALS = 
KEY_0 = ksEmissive
VALUE_0 = 255, 229, 255, 0.002
VALUE_0_OFF = 0, 0, 0
KEY_1 = ksAlphaRef
VALUE_1 = -193
VALUE_1_OFF = 0
CONDITION = NIGHT_SMOOTH

[LIGHT_SERIES_9]
ACTIVE = 1
DESCRIPTION = 
MATERIALS = garage_main_13
OFFSET = 0,0,0
DIRECTION = 0,-1,0
SPOT = 170
SPOT_SHARPNESS = 0.5
RANGE = 40
RANGE_GRADIENT_OFFSET = 0.4
FADE_AT = 1000
FADE_SMOOTH = 25
COLOR = 238, 221, 130, 0.05
CLUSTER_THRESHOLD = 18
DIFFUSE_CONCENTRATION = 0.5
CONDITION = ALWAYS_ON

[MATERIAL_ADJUSTMENT_9]
ACTIVE = 1
VISIBILITY_LEVEL = 1
DESCRIPTION = 
MATERIALS = garage_main_13
KEY_0 = ksEmissive
VALUE_0 = 238, 221, 130, 0.05
VALUE_0_OFF = 0, 0, 0
KEY_1 = ksAlphaRef
VALUE_1 = -193
VALUE_1_OFF = 0
CONDITION = ALWAYS_ON

[Material_Water]
Materials = tr_water_a
UseAlphaFromNormal = 1
UseRecommendedTextures = 1
UseRecommendedDetailTexture = 1
UseNormalMapTwice = 1
Type = POND

[GRASS_FX]
GRASS_MATERIALS = tr_grass_main, tr_grass_bank
GRASS_MESHES = 
OCCLUDING_MESHES = 
OCCLUDING_MATERIALS = 
OCCLUDING_MATERIALS_ALPHA = tr_terrain_sponsors_e, kerb_giallo_a, kerb_giallo_b, kerb_giallo_c
ORIGINAL_GRASS_MATERIALS= 
MASK_BLUR = 1
SHAPE_SIZE = 3, 1
SHAPE_TIDY = 0.5   
SHAPE_CUT = 0.5    
SHAPE_WIDTH = 2.0
TRIM_PERIOD = 365 
MASK_MAIN_THRESHOLD = 1.0
MASK_RED_THRESHOLD = 0.02
MASK_MIN_LUMINANCE = 0.02
MASK_MAX_LUMINANCE = 0.1
TEXTURE =  grass_fx/highlands.dds
TEXTURE_GRID =8, 3

[GRASS_FX_TEXTURE_GROUP_0]
PIECE_0 = 1, 1
PIECE_0_CHANCE = 0.25
PIECE_1 = 1, 2, 2, 1
PIECE_1_CHANCE = 0.05
PIECE_2 = 4, 1, 2, 2
PIECE_2_CHANCE = 0.5
PIECE_3 = 6, 1
PIECE_4 = 7, 1
PIECE_5 = 8, 1

[GRASS_FX_CONFIGURATION_A]
SHAPE_SIZE = 1.0, 3.5
SHAPE_CUT = 1, 0
SHAPE_TIDY = 1, 0.5
TRIM_PERIOD = 30
MASK_MAIN_THRESHOLD = 0.6
MASK_MAX_LUMINANCE = 0.1
TEXTURE_BASE_CHANCE = 1
TEXTURE_GROUP_0_CHANCE = 0.2

[GRASS_FX_CONFIGURATION_B]
SHAPE_SIZE = 3.5, 6.0
SHAPE_CUT = 0
SHAPE_TIDY = 0
TRIM_PERIOD = 365
MASK_MAIN_THRESHOLD = 0.4
MASK_MAX_LUMINANCE = 0.105
TEXTURE_BASE_CHANCE = 1
TEXTURE_GROUP_0_CHANCE = 0.5

[GRASS_FX_ADJUSTMENT_...]
MATERIALS = 
MAP = A

[GRASS_FX_ADJUSTMENT_...]
MATERIALS = 
MAP = B

[RAIN_FX]
PUDDLES_MATERIALS = asphalt_road, tr_white_line_a, tr_drainage_a, tr_brick_edges_a, tr_bridge_grass, tr_tarmac_a, tr_terrain_sponsors_a, tr_terrain_sponsors_m, tr_terrain_sponsors_o, tr_terrain_sponsors_n, tr_terrain_sponsors_b, tr_offtrack_a, tr_tarmac_outfield_a, tr_astro_a, tr_terrain_sponsors_l, tr_rumble_b, tr_drainage_c, tr_rumble_a, skid, tr_skidmarks, tr_skidmarks_02, groove, tr_rumble_c, tr_terrain_sponsors_g, tr_grid_b_grass_a, tr_bridge_grass_thin, tr_terrain_sponsors_e, tr_tarmac_green, tr_terrain_sponsors_k, sha_barrier_pitwall_a_01, sha_pitwall_combined_01, tr_tarmac_outfield_b, tr_macro_roads, tr_pitgarages_aa_02, tr_pitgarages_ab_02, tr_pitgarages_ac_02, tr_pitgarages_ad_02, tr_pitgarages_ad_05, tr_red_line_a, pit_decal_01, kerb_giallo_a, kerb_giallo_b, kerb_giallo_c
SOAKING_MATERIALS = 
SMOOTH_MATERIALS = 
ROUGH_MATERIALS = 

[ANIMATED_...]
NODE = helicopter_01
ANIMATION = 
DURATION = 192

[ANIMATED_...]
NODE = helicopter_02
ANIMATION = 
DURATION = 120

[SHADER_REPLACEMENT_...]
MATERIALS = Rotor
SHADER = stPerPixelNM_UVflow
PROP_0 = offsetNMSpeed, 6.3, 0

[SHADER_REPLACEMENT_...]
MATERIALS = Rotor2
SHADER = stPerPixelNM_UVflow
PROP_0 = offsetNMSpeed, 6.3, 0

[CONDITION_...]
NAME = BLINK
INPUT = ONE
FLASHING_FREQUENCY = 5
FLASHING_SMOOTHNESS = 0
FLASHING_SKIP_OFF_STATE = 0
FLASHING_NOISE_AMPLITUDE = 0
FLASHING_MIN_VALUE = 0.0
FLASHING_SYNCED = 1

[CONDITION_...]
NAME = BLINK_ALT
INPUT = ONE
FLASHING_FREQUENCY = -5
FLASHING_SMOOTHNESS = 0
FLASHING_SKIP_OFF_STATE = 0
FLASHING_NOISE_AMPLITUDE = 0
FLASHING_MIN_VALUE = 0.0
FLASHING_SYNCED = 1

[MATERIAL_ADJUSTMENT_...]
ACTIVE = 1
DESCRIPTION = light on
MATERIALS = lights_marshal_a_02
KEY_0 = ksEmissive
VALUE_0 = 0,255,0,0.05
VALUE_0_OFF = 0
CONDITION = BLINK

[MATERIAL_ADJUSTMENT_...]
ACTIVE = 1
DESCRIPTION = light on
MATERIALS = light_auxrace_b
KEY_0 = ksEmissive
VALUE_0 = 0,255,0,0.05
VALUE_0_OFF = 0
CONDITION = BLINK

[MATERIAL_ADJUSTMENT_...]
ACTIVE = 1
DESCRIPTION = light on
MATERIALS = lights_pit_exit_a_02b
KEY_0 = ksEmissive
VALUE_0 = 0,255,0,0.05
VALUE_0_OFF = 0
CONDITION = BLINK

[MATERIAL_ADJUSTMENT_...]
ACTIVE = 1
DESCRIPTION = heli green
MATERIALS = heligreen, Hughes500_GreenLight, safety_light2
KEY_0 = ksEmissive
VALUE_0 = 0,255,0,1
VALUE_0_OFF = 0
CONDITION = BLINK

[MATERIAL_ADJUSTMENT_...]
ACTIVE = 1
DESCRIPTION = heli red
MATERIALS = helired, Hughes500_RedLight, safety_light
KEY_0 = ksEmissive
VALUE_0 = 255,0,0,2
VALUE_0_OFF = 0
CONDITION = BLINK_ALT

[MATERIAL_ADJUSTMENT_...]
ACTIVE = 1
DESCRIPTION = heli cockpit
MATERIALS = heliinside, Hughes500_Navlights
KEY_0 = ksEmissive
VALUE_0 = 55,255,55,0.25
VALUE_0_OFF = 0
CONDITION = NIGHT_SMOOTH

[MATERIAL_ADJUSTMENT_...]
ACTIVE = 1
VISIBILITY_LEVEL = 1
DESCRIPTION = make heli sky flooder visible at night
MATERIALS = helispot
KEY_0 = alpha
VALUE_0 = 0.5
VALUE_0_OFF = ORIGINAL
KEY_1 = ksAlphaRef
VALUE_1 = 1
VALUE_1_OFF = ORIGINAL
KEY_2 = ksDiffuse
VALUE_2 = 1
VALUE_2_OFF = ORIGINAL
BLEND_MODE = ALPHA_BLEND
 ;BLEND_MODE=ALPHA_TEST
CONDITION = NIGHT_SMOOTH

[MATERIAL_ADJUSTMENT_...]
ACTIVE = 1
VISIBILITY_LEVEL = 1
DESCRIPTION = make heli sky flooder glow
MATERIALS = helispot
KEY_0 = ksEmissive
VALUE_0 = 5
VALUE_0_OFF = ORIGINAL
CONDITION = NIGHT_SMOOTH

[ANIMATED_...]
NODE = Blimp
ANIMATION = 
DURATION = 1925

[SHADER_REPLACEMENT_...]
DESCRIPTION=paddock lights replacement
MATERIALS=Blimp.001
SHADER=ksPerPixelMultiMap_emissive
RESOURCE_4=txEmissive
RESOURCE_REF_4=txMaps

[MATERIAL_ADJUSTMENT_...]
MATERIALS=Blimp.001
KEY_0=ksEmissive
VALUE_0=255,255,255,0.1
VALUE_0_OFF=0
KEY_1=ksAlphaRef
VALUE_1=-193
VALUE_1_OFF=0
CONDITION=NIGHT_SMOOTH

[LIGHT_...]
ACTIVE=1
DESCRIPTION=blimp light
POSITION = 0, -15, 0
DIRECTION = 0, 1, 0
RELATIVE_TO = Blimp_geo_001
SPOT = 180
SPOT_SHARPNESS = 0.5
RANGE = 10
RANGE_GRADIENT_OFFSET = 0.2
COLOR = 100
VOLUMETRIC_LIGHT = 1

; ledwalls - 1st make screens blocky

[Material_DigitalScreen]
Materials = ledwal_lcd
UseTextureCoordinates = 1  ; if mapping seems weird, change to 0
                           ; (although it shouldn’t, or else how would DISPLAY_… work?)
ScreenAspectRatio = 0.5    ; adjust if pixels look skewed
ScreenScale = 384          ; adjust for target resolution, the lower the blockier
                           ; in general using texture size here might be a good idea

; Jumbotron cameras

[DISPLAY_...] ;  0
MESHES = ledwall_00?_KSLAYER
REGION_START = 0, 0   ; display position on texture, in pixels
REGION_SIZE = 512, 384   ; display size on texture, in pixels
; Update and rendering options
HIGH_REFRESH_RATE = 1    ; high refresh rate (enabled by default; 30 FPS with this option on, 15 FPS without)
FLIP_X = 1               ; change to 1 to flip output on X axis (mainly for strange UV mapping)
FLIP_Y = 1               ; change to 1 to flip output on Y axis (mainly for strange UV mapping)
; Color corrections:
OUTPUT_ALPHA = 1         ; alpha channel value for display area
OUTPUT_GAMMA = 0.55      ; gamma correction, reduce to make darker areas even darker
OUTPUT_SATURATION = 1.0  ; saturation correction
OUTPUT_BRIGHTNESS = 1.0  ; brightness correction
OUTPUT_FISH_EYE = 0.0    ; increase to add lens distortion effect
OUTPUT_VIGNETTE = 0.0    ; increase to darken corners
OUTPUT_CHROMATIC_ABERRATION = 0.0 ; increase to add that nasty chromatic aberration
MODE = CAMERA

CAMERA_0 = -572.889 ,20.7154 ,485.96
CAMERA_0_TARGET = FOCUSED_CAR  ; instead of fixed point, uses closes car
CAMERA_0_TARGET_INERTIA = 0.1  ; camera inertia for smoother movement
CAMERA_0_FOV = 25

CAMERA_1 = -378.702 ,6.705 ,365.92
CAMERA_1_TARGET = FOCUSED_CAR  ; instead of fixed point, uses closes car
CAMERA_1_TARGET_INERTIA = 0.1  ; camera inertia for smoother movement
CAMERA_1_FOV = 25

CAMERA_2 = -426.952 ,3.49945 ,143.692
CAMERA_2_TARGET = FOCUSED_CAR  ; instead of fixed point, uses closes car
CAMERA_2_TARGET_INERTIA = 0.1  ; camera inertia for smoother movement
CAMERA_2_FOV = 25

CAMERA_3 = -529.921 ,12.2499 ,-55.0612
CAMERA_3_TARGET = FOCUSED_CAR  ; instead of fixed point, uses closes car
CAMERA_3_TARGET_INERTIA = 0.1  ; camera inertia for smoother movement
CAMERA_3_FOV = 25

CAMERA_4 = -79.6682 ,6.02232 ,-42.4385
CAMERA_4_TARGET = FOCUSED_CAR  ; instead of fixed point, uses closes car
CAMERA_4_TARGET_INERTIA = 0.1  ; camera inertia for smoother movement
CAMERA_4_FOV = 25

CAMERA_5 = 75.0592 ,9.50866 ,11.8648
CAMERA_5_TARGET = FOCUSED_CAR  ; instead of fixed point, uses closes car
CAMERA_5_TARGET_INERTIA = 0.1  ; camera inertia for smoother movement
CAMERA_5_FOV = 25

CAMERA_6 = -110.743 ,4.00354 ,-383.81
CAMERA_6_TARGET = FOCUSED_CAR  ; instead of fixed point, uses closes car
CAMERA_6_TARGET_INERTIA = 0.1  ; camera inertia for smoother movement
CAMERA_6_FOV = 25

CAMERA_7 = -120.291 ,9.71156 ,-592.555
CAMERA_7_TARGET = FOCUSED_CAR  ; instead of fixed point, uses closes car
CAMERA_7_TARGET_INERTIA = 0.1  ; camera inertia for smoother movement
CAMERA_7_FOV = 25

CAMERA_8 = 548.761 ,25.6984 ,567.736
CAMERA_8_TARGET = FOCUSED_CAR  ; instead of fixed point, uses closes car
CAMERA_8_TARGET_INERTIA = 0.1  ; camera inertia for smoother movement
CAMERA_8_FOV = 25

CAMERA_9 = 379.108 ,8.14711 ,261.208
CAMERA_9_TARGET = FOCUSED_CAR  ; instead of fixed point, uses closes car
CAMERA_9_TARGET_INERTIA = 0.1  ; camera inertia for smoother movement
CAMERA_9_FOV = 25

[SHADER_REPLACEMENT_...]
MATERIALS = rolex_board_c_01
SHADER = stPerPixelNM_UVflow
PROP_0 = offsetDSpeed, 0, 0.1
PROP_1 = pauseTiming, 4, 0

[SHADER_REPLACEMENT_...]
MATERIALS = schermo_3
SHADER = stPerPixelNM_UVflow
PROP_... = offsetDSpeed, 0, 0.025
PROP_... = pauseTiming, 4, 0
PROP_... = ksAmbient, 0.3
PROP_... = ksDiffuse, 0.0
PROP_... = ksSpecular, 0
PROP_... = ksSpecularEXP, 100
PROP_... = ksEmissive, 5 0.05

[SHADER_REPLACEMENT_...]
MATERIALS = aramco_medium_blend_board
SHADER = stPerPixelNM_UVflow
PROP_... = offsetDSpeed, 0.0, 0.125
PROP_... = pauseTiming, 0.125, -1
PROP_... = ksAmbient, 0.3
PROP_... = ksDiffuse, 0.0
PROP_... = ksSpecular, 0
PROP_... = ksSpecularEXP, 100
PROP_... = ksEmissive, 5 0.05

[SHADER_REPLACEMENT_...]
MATERIALS = tr_seventy_board_black, pzero_board_a, dhl_board_c_02, fly_emirates_board_a, rolex_board_b_01
SHADER = stPerPixelNM_UVflow
PROP_0 = offsetDSpeed, 0, 0.1
PROP_1 = pauseTiming, 4, 0

[SHADER_REPLACEMENT_...]
MATERIALS = display_rolex
SHADER = stPerPixelNM_UVflow
PROP_... = offsetDSpeed, 0.05, 0
PROP_... = ksAmbient, 0.3
PROP_... = ksDiffuse, 0.0
PROP_... = ksSpecular, 0
PROP_... = ksSpecularEXP, 100
PROP_... = ksEmissive, 3 0.015