[LIGHTING]
SPECULAR_MULT=1.2
LIT_MULT=1.85
CAR_LIGHTS_LIT_MULT=1.4

[WIND]
DYNAMIC_FLAGS = AUTO

[INCLUDE]
INCLUDE=common/conditions.ini

[GRASS_FX]
GRASS_MATERIALS = grass1a, dirtedge, graveltrans, scenery01, grassout_new
OCCLUDING_MATERIALS_ALPHA = ZICLOGO
OCCLUDING_MESHES = 
ORIGINAL_GRASS_MATERIALS = 
MASK_BLUR = 1
SHAPE_SIZE = 0.8, 1.0
SHAPE_TIDY = 0
SHAPE_CUT = 1.5
TRIM_PERIOD = 365

[GRASS_FX_CONFIGURATION_A]
SHAPE_SIZE = 3, 3
TRIM_PERIOD = 365

[GRASS_FX_CONFIGURATION_B]
SHAPE_SIZE = 3, 3
TRIM_PERIOD = 365

[GRASS_FX_ADJUSTMENT_9002]
MATERIALS = grass1a, dirtedge, graveltrans, scenery01, grassout_new
USE_MULTILAYER_MASK = 1
MASK_R = A, 5
MASK_G = -20
MASK_B = B, 5
MASK_A = C

[SHADER_REPLACEMENT_0]
MATERIALS = zhu_bush_2
REM__9 = ;MESHES = zhu_tree_bush
LOD_OUT = 800

[Material_DistantEmissive]
Materials=light_lamp_1
FloodlightPower=2
DistanceMult_v2=0.0
DotBrightnessCenter_v2=2.5

;;;;;;;;;;

[LIGHT_SERIES_0]
ACTIVE=1
VISIBILITY_LEVEL=0
DESCRIPTION=all big 4 spotted lights
MATERIALS=light_lamp_1
OFFSET=0,0,0
DIRECTION=DIRECTION=0,-1,0
SPOT=180
SPOT_SHARPNESS=0.76
RANGE=70
RANGE_GRADIENT_OFFSET=0.4
FADE_AT=1000
FADE_SMOOTH=40
CLUSTER_THRESHOLD=30
SINGLE_FREQUENCY=0.5
COLOR=234,121,36,0.05
COLOR_OFF=255,183,76,0
CONDITION=NIGHT_SMOOTH

[MATERIAL_ADJUSTMENT_0]
ACTIVE=1
VISIBILITY_LEVEL=0
DESCRIPTION=all big 4 spotted lights glow
MATERIALS=light_lamp_1
KEY_0=ksEmissive
VALUE_0=234,121,36,0.5
VALUE_0_OFF=0, 0, 0
KEY_1=ksAlphaRef
VALUE_1=-193
VALUE_1_OFF=0, 0, 0
CONDITION=NIGHT_SMOOTH


[LIGHT_SERIES_1]
ACTIVE = 1
DESCRIPTION = 
MATERIALS = pitlamp0
OFFSET = 0,0,0
DIRECTION = 0,-1,0
SPOT = 180
SPOT_SHARPNESS = 0.5
RANGE = 40
RANGE_GRADIENT_OFFSET = 0.4
FADE_AT = 1000
FADE_SMOOTH = 25
COLOR = 255, 229, 255, 0.05
CLUSTER_THRESHOLD = 18
DIFFUSE_CONCENTRATION = 0.5
CONDITION = NIGHT_SMOOTH

[MATERIAL_ADJUSTMENT_1]
ACTIVE = 1
VISIBILITY_LEVEL = 1
DESCRIPTION = 
MATERIALS = pitlamp0
KEY_0 = ksEmissive
VALUE_0 = 255, 229, 255, 0.5
VALUE_0_OFF = 0, 0, 0
KEY_1 = ksAlphaRef
VALUE_1 = -193
VALUE_1_OFF = 0
CONDITION = NIGHT_SMOOTH

[LIGHT_SERIES_2]
ACTIVE = 1
DESCRIPTION = neon
MATERIALS = gst_light
OFFSET = 0,0,0
SPOT = 180
SPOT_SHARPNESS = 0.5
RANGE = 30
RANGE_GRADIENT_OFFSET = 0.25
FADE_AT = 700
FADE_SMOOTH = 30
DIRECTION = NORMAL
COLOR = 131, 255, 123, 0.05
CLUSTER_THRESHOLD = 15
DIFFUSE_CONCENTRATION = 0.8
CONDITION = NIGHT_SMOOTH

[MATERIAL_ADJUSTMENT_2]
ACTIVE = 1
VISIBILITY_LEVEL = 1
DESCRIPTION = neon
MATERIALS = gst_light
KEY_0 = ksEmissive
VALUE_0 = 131, 255, 123, 0.3
VALUE_0_OFF = 0, 0, 0
KEY_1 = ksAlphaRef
VALUE_1 = -193
VALUE_1_OFF = 0
CONDITION = NIGHT_SMOOTH

[LIGHT_SERIES_3]
ACTIVE = 1
DESCRIPTION = neon
MATERIALS = zhu_ambulance_2, zhu_cherrypick_2, zhu_van_base_3, zhu_safety_2, zhu_flatbed_2, zhu_recovery_2, zhu_forklift_5, zhu_tv_van_2, glassalpha
OFFSET = 0,0,0
SPOT = 180
SPOT_SHARPNESS = 0.5
RANGE = 30
RANGE_GRADIENT_OFFSET = 0.25
FADE_AT = 700
FADE_SMOOTH = 30
DIRECTION = NORMAL
COLOR = 131, 255, 123, 0.05
CLUSTER_THRESHOLD = 15
DIFFUSE_CONCENTRATION = 0.8
CONDITION = NIGHT_SMOOTH

[MATERIAL_ADJUSTMENT_3]
ACTIVE = 1
VISIBILITY_LEVEL = 1
DESCRIPTION = neon
MATERIALS = zhu_ambulance_2, zhu_cherrypick_2, zhu_van_base_3, zhu_safety_2, zhu_flatbed_2, zhu_recovery_2, zhu_forklift_5, zhu_tv_van_2, glassalpha
KEY_0 = ksEmissive
VALUE_0 = 131, 255, 123, 0.3
VALUE_0_OFF = 0, 0, 0
KEY_1 = ksAlphaRef
VALUE_1 = -193
VALUE_1_OFF = 0
CONDITION = NIGHT_SMOOTH

[RAIN_FX]
PUDDLES_MATERIALS = road1, lgroad1, skid_brake5, rmblarw, b2road, rmblar, b3road, roadsupport, skid_brake4, concrw, concfencebase, marsh_1, roadpitexit1, roadpit, concarrow, roadpitlane1, roadconc01, roadpitconc01, pitwall2
SOAKING_MATERIALS = 
SMOOTH_MATERIALS = 
ROUGH_MATERIALS = 

