[INCLUDE]
INCLUDE=common/conditions.ini, common/materials_track.ini, common/materials_glass.ini, common/materials_pbr.ini

; Base PBR parameters, available to all of these PBR shaders.
[_Base_Material_PBR]
F0 = 0.04                ; base reflectivity for non-metal materials with metalness workflow
Emissive = 0, 0, 0       ; emissive value
AlbedoGain = 1, 1, 1     ; RGB multiplier for albedo texture
BlurCubemap = 0          ; forcefully blur cubemap (use it to reduce details in reflections in areas where cubemap does not fit well)

; Flags:
SpecularWorkflow = 0       ; by default metalness workflow is used, set this to 1 to switch to specular (or set optional TextureSpecular value for materials that support it)
ApplyTilingFix = 0         ; apply tiling fix (not available with parallax)
SceneryAO = 0              ; set to 1 if you for some reason have non-material AO in TextureEmAoMeRo ambient occlusion channel, it would disable micro shadow and AO fresnel
SkipAlbedoForEmissive = 0  ; do not use albedo for emissive color
DXT5NMNormalMap = 0        ; set to 1 if normal map is in DXT5NM format (some texture slots of some materials might not support it, check the comments)

; Optional parallax. To use, set this texture to height map (only for materials that support it):
TextureDisplacement =    ; currently, texture has to be square
DisplacementMax = 50     ; maximum distance at which displacement is active
DisplacementMin = 30     ; minimum distance at which displacement is active
ParallaxScale = 0.02     ; parallax depth
ParallaxSteps = 20       ; maximum number of steps, increase to improve visual quality (expensive)
ParallaxOffset = 0.5     ; what value of displacement texture is considered neutral, 0.5 for gray, 0 for white, 1 for black
ParallaxUVToWorld = 0    ; set to UV-to-world scale value to get parallax offset to shift shadow maps and dynamic lights, works well if the object is mapped evenly
                         ; (possibly a temporal option until I figure out a way to compute that scale live reliably)


; Basic PBR shader with extra variance and scenery AO in UV2 (or, alternatively, using scaled UV1 for PBR textures and unscaled UV1 for variance and scenery AO).
; Scenery AO is AO from object surroundings and its geometry, in other words storing those blurry shadows. Unlike it, PBR AO is highly detailed AO drawn for actual
; material (for example, for a brick wall space between bricks might be darker on AO map).

[Material_PBR]
UVScale = 1  ; scale for UV1

; Textures:
TextureAlbedo =      ; albedo map without ambient occlusion
TextureNormal =      ; normal texture, only red and green channels are read (DXT5NM format is supported with “DXT5NMNormalMap” flag)
TextureEmAoMeRo =    ; emissive, ambient, metalness and roughness maps in RGBA channels accordingly (arranged for better visual with DXT5/BC7 compression)¹
TextureSpecular =    ; specular map, used only with specular workflow; if not set, metalness map is used as specular map
TextureVarianceAO =  ; optional albedo variance and additional AO map, uses UV2 (only active when corresponding flags are set)

; Flags:
ApplyAOMap = 0          ; apply extra AO map from TextureVarianceAO
ApplyVarianceMap = 0    ; apply albedo variance map from TextureVarianceAO (applied as multiplier)
UseUnscaledUV1For2 = 0  ; use unscaled UV1 instead of UV2 for txVarianceAO (allows to sort of recreate “ksPerPixelMultiMap_NMDetail” logic)




[GRASS_FX]
; Spawning areas
GRASS_MATERIALS = Ground?, Grass?, aerial_rocks_04 ; list of materials to spawn grass on top of
GRASS_MESHES = ; same for meshes
OCCLUDING_MATERIALS = ?Cliff?, ?asphalt?, ?Concrete?, ?wall?, ?road?, ?water?, GrungeWall03, Road001, Concrete_018, white_plaster_rough_02, broken_wall ; list of occluding materials: for example, road mesh covering grass mesh, adding road material here would stop grass from showing through the road
OCCLUDING_MESHES = ; same for meshes
OCCLUDING_MATERIALS_ALPHA = ; list of smoothly occluding materials: imagine a piece of grass and a piece of sand on top, smoothly blending out showing grass, add sand material here for transition to work nicely
OCCLUDING_MESHES_ALPHA = ; same for meshes
ORIGINAL_GRASS_MATERIALS = ; list original grass materials to hide them if Grass FX is active
; NOTE: if you want to keep original 3dgrass (using ksGrass shader), then use an
; EMPTY line above with NO NAME after the "=" !!!

MASK_MAIN_THRESHOLD = -1
MASK_RED_THRESHOLD = 0
MASK_MIN_LUMINANCE = -1
MASK_MAX_LUMINANCE = 1

SHAPE_SIZE = 10.0 ; general size
SHAPE_TIDY = 3.0 ; how tidy grass is (untidy grass in uneven, tilted more)
SHAPE_CUT = 0.0 ; how cut grass is
SHAPE_WIDTH = 1.0 ; grass width relative to its height

[ALIGN_TREES_...]
SURFACE_MATERIALS = aerial_rocks_04
TREE_MATERIALS = shader:ksTree

[SHADER_REPLACEMENT_...]
MATERIALS = shader:ksTree?
MATERIAL_FLAG_0 = 1

[SHADER_REPLACEMENT_...],
MATERIALS= TREE PL, topwindowscreensquarescreen1material, Fabric036, cablecar-wire1
MESHES = Cube.2006, Cube.108,Cube.325 ,Cube.712, Cube.713, Cylinder.013, Cylinder.014
CULL_MODE=DOUBLESIDED

[SHADER_REPLACEMENT_1]
MATERIALS = spot-lights-road
KEY_0 = extExtraSharpLocalReflections
VALUE_0 = 1
KEY_1 = ksSpecularEXP
VALUE_1 = 100

[SHADER_REPLACEMENT_2]
MATERIALS = topwindowscreensquarescreen1material
SHADER = ksPerPixelAT

[Material_Glass]
RESOURCE_0 = txNormal
RESOURCE_FILE_0 = Glass_Frosted_001_normal.dds
Materials = glass
IOR = 1.5
UseNormalMap = 1
ThicknessMult = 1
RefractionBias = 0.9
Refraction = 0.9
RefractionRainbow = 1
BrightnessAdjustment = 0.3
ExtraLightsAdjustment = 0.3
MaskPass = 3
FilmIOR = 3.2
PhotoelasticityMult = 0.5
PhotoelasticityBaseScale = 8      ; this parameter alters scale in general
PhotoelasticityNoiseScale = 0.04  ; deeply affects randomization process, careful with it
PhotoelasticitySpotsScale = 0.5   ; spots for limiting effect to some areas
PhotoelasticitySpotsOffset = 0.1  ; offset for spots, to try and fit effect nice on existing meshes
PhotoelasticityStripesScale = 4   ; how many stripes are there
ProfileFix = 0.1

KEY_0 = extColoredReflection
VALUE_0 = 1
KEY_1 = extColoredReflectionNorm
VALUE_1 = 1

;[SHADER_REPLACEMENT_3]
;MATERIALS = glass
;SHADER = ksPerPixelReflection
;KEY_0 = alpha
;VALUE_0 = 0
;KEY_1 = extExtraSharpLocalReflections
;VALUE_1 = 1
;KEY_2 = ksAlphaRef
;VALUE_2 = 1
;KEY_3 = isAdditive
;VALUE_3 = 1
;KEY_4 = ksAmbient
;VALUE_4 = 0.1
;KEY_5 = fresnelEXP
;VALUE_5 = 1
;KEY_6 = fresnelC
;VALUE_6 = 1
;KEY_7 = fresnelMaxLevel
;VALUE_7 = 1
;KEY_8 = ksSpecular
;VALUE_8 = 20
;KEY_9 = ksSpecularEXP
;VALUE_9 = 100

[BASIC]
SUPPORTS_WIND = 1
IGNORE_OTHER_CONFIGS = 1

[WIND]
IGNORE =            ; disable wind for certain meshes
DYNAMIC_FLAGS = AUTO          ; Valid values: NONE, AUTO, or regular mesh filter
TREES_NORMALIZATION = 0.8, 1  ; Stretch trees normalization area so original 0.9 would become 0
GRASS_NORMALIZATION = 0.8, 1  ; Stretch grass normalization area so original 0.9 would become 0
RANDOMIZED_OFFSET_BASE = 4.0            ; ? 4.f
RANDOMIZED_OFFSET_REL = 0.0             ; ? 0.5f
RANDOMIZED_OFFSET_CHANGE_SPEED = 5.0    ; ? 5.f
RANDOMIZED_OFFSET_CHANGE_MAX = 0.0      ; ? 0.8f

[RAIN_FX]
PUDDLES_MATERIALS = asphalt?, tiles?, Paving?, aerial_asphalt_01, Road001
SOAKING_MATERIALS = concrete?, ground?,
SMOOTH_MATERIALS = Rock?, wall?, metal?
ROUGH_MATERIALS = TREE?,
LINES_MATERIALS =
RELIEF_MATERIALS =

[Material_DisplacementMap]
Meshes = texture:Stone_Wall_009_NORM.dds, texture:aerial_rocks_01_nor_dx_1k.dds, texture:Bricks058_1K_NormalDX.dds, texture:Cliff_Rock_002_normal.dds, texture:Cliff_rock_01_normal.dds, texture:aerial_rocks_02_nor_dx_1k.dds, texture:Rock022_1K_NormalDX.dds, texture:Rock027_1K_NormalDX.dds, texture:Rock023_1K_NormalDX.dds, texture:Wall_Stone_023_Normal.dds, texture:Rock038_1K_NormalDX.dds, texture:tianmen-top-stone-front-platform-gold-sign_normal.dds, texture:broken_wall_normal_dx_1k.dds, texture:Rocks022_1K_NormalDX.dds, texture:rough_plaster_broken_nor_dx_1k.dds, texture:grey_roof_tiles_nor_dx_1k.dds, texture:Bricks075A_1K_NormalDX.dds, texture:MossyWall02_1K_Normal.dds, texture:Concrete_016_normal.dds, texture:Tiles010_1K_NormalDX.dds, texture:Wall_Plaster_001_normal.dds, texture:paintedPlaster015_1K_NormalDX.dds, texture:paintedPlaster001_1K_NormalDX.dds
UseParallaxShadows = 1 ; use parallax shadows (slower)
UseTessellation = 0
TessellationFactorMin = 1   ; for tesselation, how much to split mesh at the distance
TessellationFactorMax = 20  ; how much to split mesh nearby
DisplacementDistanceFar = 80.0  ; how far displacement is calculated
DisplacementDistanceNear = 20  ; at what distance displacement starts to fade out
DisplacementScale = 3.0         ; scale for displacement
DisplacementOcclusion = 0.3     ; how dark are deepest parts
ParallaxEXP = 0.9 ; increase to adjust gamma of heightmap
DisplacementInvert = 0 ; invert height map (just in case)

[CONDITION_0]
NAME=SMOOV_SUN_B
INPUT=SUN
LUT=(|0=0|88=0|88=1|180=1)
LAG=0.97

[CONDITION_1]
NAME = SEASON_SUMMER
INPUT = YEAR_PROGRESS
LUT = (|-1=0|0=1|0.45=0|0.6=0.85|0.7=0|0.75=0|0.8=1|1=1|)
LAG = 0

[CONDITION_2]
NAME = SEASON_WINTER
INPUT = YEAR_PROGRESS
LUT = (|-1=0|0=0.75|0.075=1|0.2=0|0.8=0|0.9=0.5|1=0.75|)
LAG = 0

[CONDITION_3]
NAME = SEASON_AUTUMN
INPUT = YEAR_PROGRESS
LUT = (|-1=0|0=1|0.2=0|0.45=0|0.6=0.25|0.7=0|0.75=0|0.8=1|1=1|)
LAG = 0

[CONDITION_4]
NAME = SEASON_MUD
INPUT = YEAR_PROGRESS
LUT = (|-1=0|-1=0|0=0|0.1=0|0.2=0.65|0.3=0|0.71=0|0.8=0.7|0.9=0|1=0|)
LAG = 0

[SHADER_REPLACEMENT_...]
MATERIALS = water
SHADER = smWaterSurface
RESOURCE_0 = txDiffuse
RESOURCE_FILE_0 = water.dds
RESOURCE_1 = txNormal
RESOURCE_FILE_1 = water_bump.dds
RESOURCE_2 = txDetailNM
RESOURCE_FILE_2 = water_bump.dds
KEY_0 = extCausticsBrightness
VALUE_0 = 1
KEY_1 = extDepthAware
VALUE_1 = 1
KEY_2 = extExtraSharpLocalReflections
VALUE_2 = 1
KEY_3 = extWaterOffset
VALUE_3 = 1
KEY_4 = ksSpecularEXP
VALUE_4 = 100

[Material_Water]
Materials = water, Foam001
Type = lake
UseNormalMapTwice = 1
UseAlphaFromDiffuse = 1
UseRecommendedTextures = 1
DepthAware = 1
extExtraSharpLocalReflections = 1

[LIGHTING]
ENABLE_TREES_LIGHTING = 1        ; if all your trees are not very close to a track, you can improve performance a lot by disabling trees lighting completely
;TRACK_AMBIENT_GROUND_MULT = 0.5  ; only define it if needed! allows to redefine ambient multiplier for surfaces facing down
BOUNCED_LIGHT_MULT = 1, 1, 1, 1  ; multiplier for bouncing light (set to 0 if track is black, for example)
LIT_MULT = 1                     ; multiplier for dynamic lights affecting the track
SPECULAR_MULT = 0.01                ; multiplier for speculars
CAR_LIGHTS_LIT_MULT = 1          ; multiplier for dynamic lights affecting cars on the track
TERRAIN_SHADOWS_THRESHOLD = 1.1  ; ?

[BOUNCED_LIGHT]
SUPPORTED = 1
DEPTH_EXPANSION_STEPS = 1
SURFACE_MATERIALS = ?
CAUSTICS = 1
CAUSTICS_SCALE = 1  ; optionally, adjust caustics intensity

;cable cars

[WRAP_MESHES_...]
NAME = middle-cablecar-1
MESHES = cable-car-cabin-1
PIVOT_POS = 0,0,0
;PIVOT_DIR 0,-90,-1 ; last working  0,-90,-1
;PIVOT_UP = 0, 0, 0 
PIVOT_HEADING = 1.5707
PIVOT_PITCH = 3.1415
PIVOT_ROLL = -1.5707

[ANIMATED_...]
NODE = middle-cablecar-1 ; node to move. Put the first car of the train here.
MOVE_ALONG = Plane.048 ; move along this mesh (this line sets the movement mode)
NODES_FOLLOWING = middle-cablecar-1.001, middle-cablecar-1.002, middle-cablecar-1.003, 
CLUSTER_THRESHOLD = 7 ; required for finding trajectory from train_path properly - Increase this if you dont get a continous path when DEBUG_PATH = 1
CUBIC_INTERPOLATION = 1 ; smooth out path
SPEED_KMH = 20 ; basic train speed
PIECE_LENGTH = 10
LAG_UP = 0.99
LAG_DOWN = 0.9
DEBUG_PATH = 0
INVERT_DIRECTION = 1

;[ANIMATED_...]
;NODE = middle-cablecar-1 ; node to move. Put the first car of the train here.
;MOVE_ALONG = Plane.047 ; move along this mesh (this line sets the movement mode)
;NODES_FOLLOWING = middle-cablecar-2, middle-cablecar-3, middle-cablecar-4, 
;CLUSTER_THRESHOLD = 1 ; required for finding trajectory from train_path properly - Increase this if you dont get a continous path when DEBUG_PATH = 1
;CUBIC_INTERPOLATION = 1 ; smooth out path
;SPEED_KMH = 20 ; basic train speed
;PIECE_LENGTH = 10
;LAG_UP = 0.99
;LAG_DOWN = 0.9
;DEBUG_PATH = 1
;INVERT_DIRECTION = 1

[SHADER_REPLACEMENT_...]
MATERIALS = cable-car-cabin-1
SHADER = fuPBR
RESOURCE_0 = txAlbedo
RESOURCE_FILE_0 = cable-car-cabin-1_color.dds
RESOURCE_1 = txEmAoMeRo
RESOURCE_FILE_1 = cable-car-cabin-1_eamr.dds
RESOURCE_2 = txNormal2
RESOURCE_FILE_2 = cable-car-cabin-1_normal.dds

KEY_0 = pbrAlbedoGain
VALUE_0 = 0.5
KEY_1 = uvScale
VALUE_1 = 1
KEY_2 = extExtraSharpLocalReflections
VALUE_2 = 0
KEY_3 = pbrF0
VALUE_3 = 0.05

[SHADER_REPLACEMENT_...]
MATERIALS = SeasideRocks01
SHADER = fuPBR_parallax
RESOURCE_0 = txAlbedo
RESOURCE_FILE_0 = SeasideRocks01_1K_Color.dds
RESOURCE_1 = txEmAoMeRo
RESOURCE_FILE_1 = SeasideRocks01_1K_eamr.dds
RESOURCE_2 = txNormal2
RESOURCE_FILE_2 = SeasideRocks01_1K_Normal.dds
RESOURCE_3 = txDisplacement
RESOURCE_FILE_3 = SeasideRocks01_1K_Height.dds

KEY_0 = pbrAlbedoGain
VALUE_0 = 0.5
KEY_1 = uvScale
VALUE_1 = 1
KEY_2 = extExtraSharpLocalReflections
VALUE_2 = 1
KEY_3 = pbrF0
VALUE_3 = 0.01
KEY_4 = extParallaxScale
VALUE_4 = 0.1
KEY_5 = extParallaxSteps
VALUE_5 = 64
KEY_6 = extDisplacementRangeBase
VALUE_6 = 0.1
KEY_7 = extParallaxTexToWorld
VALUE_7 = 1

[SHADER_REPLACEMENT_...]
MATERIALS = Metal015
SHADER = fuPBR_parallax
RESOURCE_0 = txAlbedo
RESOURCE_FILE_0 = Metal_Gold_001_color.dds
RESOURCE_1 = txEmAoMeRo
RESOURCE_FILE_1 = Metal_Gold_001_eamr.dds
RESOURCE_2 = txNormal2
RESOURCE_FILE_2 = Metal_Gold_001_normal.dds
RESOURCE_3 = txDisplacement
RESOURCE_FILE_3 = Metal_Gold_001_height.dds
RESOURCE_4 = txSpecular
RESOURCE_FILE_4 = ...

KEY_0 = pbrAlbedoGain
VALUE_0 = 0.5
KEY_1 = uvScale
VALUE_1 = 1
KEY_2 = extExtraSharpLocalReflections
VALUE_2 = 0
KEY_3 = pbrF0
VALUE_3 = 0.01
KEY_4 = extParallaxScale
VALUE_4 = 0.1
KEY_5 = extParallaxSteps
VALUE_5 = 20
KEY_6 = extDisplacementRangeBase
VALUE_6 = 0.1
KEY_7 = extParallaxTexToWorld
VALUE_7 = 1